"""add appearance settings

Revision ID: 0153640fa985
Revises: 4e489fad4d63
Create Date: 2026-07-21 13:44:23.822444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0153640fa985'
down_revision = '4e489fad4d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appearance_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('color_mode', sa.String(length=10), nullable=False),
    sa.Column('background_filename', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appearance_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appearance_setting_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appearance_setting_user_id'))

    op.drop_table('appearance_setting')
    # ### end Alembic commands ###
