"""add assistant conversations

Revision ID: 66a025c924fd
Revises: e040ec86d292
Create Date: 2026-07-21 15:08:39.476784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a025c924fd'
down_revision = 'e040ec86d292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('page_type', sa.String(length=30), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversation_user_id'), ['user_id'], unique=False)

    op.create_table('ai_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('references_json', sa.Text(), nullable=False),
    sa.Column('proposal_json', sa.Text(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_message_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('ai_chat_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['ai_message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    with op.batch_alter_table('ai_chat_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chat_attachment_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chat_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chat_attachment_message_id'))

    op.drop_table('ai_chat_attachment')
    with op.batch_alter_table('ai_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_message_conversation_id'))

    op.drop_table('ai_message')
    with op.batch_alter_table('ai_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversation_user_id'))

    op.drop_table('ai_conversation')
    # ### end Alembic commands ###
