(() => {
  "use strict";
  const R=window.RLab,{$,$$,state,invoke,icons,toast,escapeHtml,dateLabel,statusBadge,emptyRow,nativeDialog,navigate,paginate,renderPagination}=R;
  let literatureSource="",literatureItems=[],literaturePage=1,literaturePageSize=20;
  let noteKind="",noteItems=[],notePage=1,notePageSize=20,filePage=1,filePageSize=20,fileImportRecordId=null;
  const literatureSelection=new Set(),noteSelection=new Set();
  $("[data-literature-select-all]")?.replaceChildren("选择当前页");
  $("[data-note-select-all]")?.replaceChildren("选择当前页");

  function projectOptions(select,includeUnclassified=true){if(!select)return;const current=select.value,base=`<option value="">全部项目</option>${includeUnclassified?`<option value="unclassified">未分类</option>`:""}`;select.innerHTML=base+state.projects.map(item=>`<option value="${item.id}">${escapeHtml(item.title)}</option>`).join("");select.value=current;}
  function syncBulkBar(id,selection,total){const bar=$(id);bar.hidden=!selection.size;if(!bar.hidden){$("[data-selected-count]",bar).textContent=selection.size;$("strong",bar).title=selection.size===total&&total>0?`已选择当前筛选的 ${total} 项`:"跨页选择会在翻页后保留";}}
  function zoteroStatusLabel(zotero){if(zotero.last_error_code==="zotero_api_disabled")return"Zotero Local API 未启用";if(zotero.last_error_code==="zotero_timeout")return"连接 Zotero 超时";if(zotero.state==="connected")return`Zotero 已连接 · 上次同步 ${dateLabel(zotero.last_success_at,true)}`;if(zotero.state==="unavailable")return"Zotero 未运行或不可用";if(zotero.state==="error")return"上次同步失败";if(zotero.state==="unknown")return"尚未连接 Zotero";return"Zotero 状态未知";}
  async function chooseValue(title,options){const trigger=document.activeElement,dialog=document.createElement("dialog");dialog.innerHTML=`<form method="dialog"><header><div><h2>${escapeHtml(title)}</h2></div></header><label>新值<select name="value">${options.map(([value,label])=>`<option value="${escapeHtml(value)}">${escapeHtml(label)}</option>`).join("")}</select></label><footer><button class="button" value="cancel">取消</button><button class="button primary" value="apply">应用</button></footer></form>`;document.body.append(dialog);dialog.showModal();return new Promise(resolve=>dialog.addEventListener("close",()=>{const value=dialog.returnValue==="apply"?new FormData($("form",dialog)).get("value"):null;dialog.remove();trigger?.focus?.();resolve(value);},{once:true}));}

  async function literature(){
    const workspace=$(".literature-workspace");if(!$("#literature-detail-toggle")){const toggle=document.createElement("button");toggle.id="literature-detail-toggle";toggle.type="button";toggle.className="icon-button detail-toggle";toggle.title="展开文献详情";toggle.innerHTML='<i data-lucide="panel-right-open"></i>';$(".resource-query",workspace).append(toggle);}
    const bulkBar=$("#literature-bulk-bar");if(bulkBar&&!$('[data-literature-bulk="trash"]',bulkBar)){const trash=document.createElement("button");trash.type="button";trash.className="button compact quiet-danger";trash.dataset.literatureBulk="trash";trash.innerHTML='<i data-lucide="trash-2"></i>移入回收站';const clear=$("[data-literature-clear]",bulkBar);bulkBar.insertBefore(trash,clear||null);}
    projectOptions($("#literature-project-filter"));
    let collectionFilter=$("#literature-collection-filter");if(!collectionFilter){const label=document.createElement("label");label.innerHTML='<span>Zotero Collection</span><select id="literature-collection-filter"><option value="">全部 Collection</option></select>';$("#literature-query").before(label);const map=document.createElement("button");map.type="button";map.id="literature-collection-map";map.className="button compact";map.title="将所选 Collection 映射到项目";map.innerHTML='<i data-lucide="git-branch"></i>映射项目';$("#literature-query").before(map);collectionFilter=$("#literature-collection-filter");}
    const selectedCollection=collectionFilter.value,collections=await invoke("zotero.collections.list",{});collectionFilter.innerHTML=`<option value="">全部 Collection</option>${collections.map(item=>`<option value="${item.id}" ${String(item.id)===selectedCollection?"selected":""}>${escapeHtml(item.name)}</option>`).join("")}`;
    const [serverPage,facets,zotero]=await Promise.all([invoke("literature.list",{pagination:true,page:literaturePage,page_size:literaturePageSize,search:$("#literature-search").value.trim(),source:literatureSource,read_status:$("#literature-status").value,project_id:$("#literature-project-filter").value,collection_id:collectionFilter.value}),invoke("literature.facets",{}),invoke("zotero.status",{})]);const items=serverPage.items;items.serverPagination=serverPage.pagination;literatureItems=items;
    $("#zotero-state").textContent=zoteroStatusLabel(zotero);$("#literature-count").textContent=`${serverPage.pagination.total} 篇文献`;
    const sourceCounts={all:0,zotero:0,manual:0,import:0,...facets.sources};for(const key of Object.keys(sourceCounts)){const node=$("#literature-source-"+key);if(node)node.textContent=sourceCounts[key];}
    const selectedProject=$("#literature-project-filter").value;$("#literature-project-rail").innerHTML=`<button data-literature-project-rail="unclassified" class="${selectedProject==="unclassified"?"active":""}"><i data-lucide="folder-x"></i><span>未分类</span></button>${state.projects.map(project=>`<button data-literature-project-rail="${project.id}" class="${selectedProject===String(project.id)?"active":""}"><i data-lucide="folder"></i><span>${escapeHtml(project.title)}</span></button>`).join("")}`;
    const page=paginate(items,literaturePage,literaturePageSize);literaturePage=page.page;$("#literature-list").innerHTML=page.items.length?`<div class="resource-table literature-table"><div class="resource-table-head literature-table-head"><label><input type="checkbox" data-literature-check-page ${page.items.every(item=>literatureSelection.has(item.id))?"checked":""} aria-label="选择当前页"></label><span>标题</span><span>作者</span><span>年份</span><span>期刊</span><span>来源</span><span>阅读状态</span><span>项目</span><span>引用记录</span></div>${page.items.map(item=>`<article class="resource-table-row literature-table-row ${state.currentLiterature?.id===item.id?"active":""}"><label class="row-selector"><input type="checkbox" data-literature-select="${item.id}" ${literatureSelection.has(item.id)?"checked":""} aria-label="选择 ${escapeHtml(item.title)}"></label><button data-literature-id="${item.id}" title="查看 ${escapeHtml(item.title)}"><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.doi||"无 DOI")}</small></span><span>${escapeHtml((item.authors||[]).join("、")||"未录入")}</span><span>${item.year||"—"}</span><span>${escapeHtml(item.journal||"未录入")}</span><span>${escapeHtml(item.source==="zotero"?"Zotero":item.source==="manual"?"本地录入":"导入")}</span>${statusBadge(item.read_status)}<span>${item.project_count||0}</span><span>${item.record_count||0}</span></button></article>`).join("")}</div>`:`<div class="empty-state"><i data-lucide="library-big"></i><p>没有匹配的文献</p></div>`;renderPagination($("#literature-pagination"),page,value=>{literaturePage=value;literature();},value=>{literaturePageSize=value;literaturePage=1;literature();});syncBulkBar("#literature-bulk-bar",literatureSelection,items.length);if(state.currentLiterature&&items.some(x=>x.id===state.currentLiterature.id))await showLiterature(state.currentLiterature.id);else if(page.items[0])await showLiterature(page.items[0].id);icons();
  }
  async function showLiterature(id){const item=await invoke("literature.get",{id});state.currentLiterature=item;$$('[data-literature-id]').forEach(x=>x.closest(".resource-table-row")?.classList.toggle("active",Number(x.dataset.literatureId)===item.id));const options=state.projects.map(x=>`<option value="${x.id}">${escapeHtml(x.title)}</option>`).join("");$("#literature-detail").innerHTML=`<header class="detail-header"><span class="eyebrow">${escapeHtml(item.source==="zotero"?"ZOTERO":"LOCAL LIBRARY")}</span><h2>${escapeHtml(item.title)}</h2><div class="detail-actions">${item.url?`<button class="button compact" data-open-url="${escapeHtml(item.url)}"><i data-lucide="external-link"></i>打开链接</button>`:""}${item.zotero_select_url?`<button class="button compact" data-open-url="${escapeHtml(item.zotero_select_url)}"><i data-lucide="library"></i>在 Zotero 中打开</button>`:""}<button class="button compact quiet-danger" data-literature-trash="${item.id}" title="移入回收站"><i data-lucide="trash-2"></i>移入回收站</button></div></header><section><h3>元数据</h3><dl class="detail-metadata"><dt>作者</dt><dd>${escapeHtml((item.authors||[]).join("；")||"未录入")}</dd><dt>年份</dt><dd>${item.year||"—"}</dd><dt>期刊</dt><dd>${escapeHtml(item.journal||"未录入")}</dd><dt>卷（期）</dt><dd>${escapeHtml([item.volume,item.issue].filter(Boolean).join("（")+(item.issue?")":"")||"—")}</dd><dt>页码</dt><dd>${escapeHtml(item.pages||"—")}</dd><dt>DOI</dt><dd>${escapeHtml(item.doi||"—")}</dd><dt>阅读状态</dt><dd>${statusBadge(item.read_status)}</dd></dl></section><section><h3>摘要与关键词</h3><p>${escapeHtml(item.abstract||"未录入摘要")}</p><div class="chip-row">${(item.keywords||[]).map(x=>`<span>${escapeHtml(x)}</span>`).join("")}</div></section><section><h3>阅读笔记</h3><p>${escapeHtml(item.reading_notes||"尚未记录阅读笔记")}</p></section><section><h3>关联脉络</h3><div class="detail-stat-list"><div><span>关联项目</span><b>${(item.project_ids||[]).length} 个</b></div><div><span>引用此文献的实验记录</span><b>${(item.record_ids||[]).length} 条</b></div></div><div class="inline-linker"><select id="literature-project-link"><option value="">选择项目</option>${options}</select><button class="button compact" data-link-literature="${item.id}">关联</button></div></section>`;icons();}
  async function trashLiterature(id,title){if(!await R.confirmAction("移入回收站",`将文献“${title||"当前文献"}”移入回收站？`))return;await invoke("trash.move",{entity_type:"literature",id:Number(id)});literatureSelection.delete(Number(id));if(state.currentLiterature?.id===Number(id)){state.currentLiterature=null;$("#literature-detail").innerHTML=`<div class="empty-state"><i data-lucide="book-open"></i><p>选择一篇文献查看详情与关联脉络</p></div>`;}await literature();toast("文献已移入回收站");}
  async function saveLiterature(event){event.preventDefault();const form=event.currentTarget;try{const payload=Object.fromEntries(new FormData(form));payload.source="manual";await invoke("literature.save",payload);form.closest("dialog").close();form.reset();await literature();toast("文献已保存");}catch(error){$(".form-error",form).textContent=error.message;}}

  function noteLabel(kind){return {idea:"研究想法",experiment_guide:"实验指引",literature:"文献笔记",meeting:"会议记录",supervisor_feedback:"导师意见",general:"普通笔记"}[kind]||kind;}
  async function notes(){projectOptions($("#note-project-filter"));const result=await invoke("note.list",{pagination:true,page:notePage,page_size:notePageSize,kind:noteKind,search:$("#note-search").value.trim(),project_id:$("#note-project-filter").value});noteItems=result.items;noteItems.serverPagination=result.pagination;const page=paginate(noteItems,notePage,notePageSize);notePage=page.page;$("#note-list").innerHTML=page.items.length?`<div class="resource-select-head"><label><input type="checkbox" data-note-check-page ${page.items.every(item=>noteSelection.has(item.id))?"checked":""}>选择当前页</label></div>${page.items.map(item=>`<article class="note-list-item ${state.currentNote?.id===item.id?"active":""}"><label class="row-selector"><input type="checkbox" data-note-select="${item.id}" ${noteSelection.has(item.id)?"checked":""}></label><button data-note-id="${item.id}"><span><b>${escapeHtml(item.title)}</b><small>${noteLabel(item.kind)} · ${dateLabel(item.updated_at,true)}</small></span><p>${escapeHtml(item.excerpt||"无正文")}</p></button></article>`).join("")}`:`<div class="empty-state"><i data-lucide="notebook-pen"></i><p>该分类还没有笔记</p></div>`;renderPagination($("#note-pagination"),page,value=>{notePage=value;notes();},value=>{notePageSize=value;notePage=1;notes();});syncBulkBar("#note-bulk-bar",noteSelection,page.total);if(state.currentNote&&noteItems.some(item=>item.id===state.currentNote.id))await showNote(state.currentNote.id);icons();}
  async function showNote(id){const item=await invoke("note.get",{id});state.currentNote=item;const form=$("#note-form");form.elements.id.value=item.id;form.elements.row_version.value=item.row_version;form.elements.title.value=item.title;form.elements.kind.value=item.kind;form.elements.project_id.value=item.project_id||"";form.elements.body.value=item.body||"";$("#note-save-state").textContent=`上次更新 ${dateLabel(item.updated_at,true)}`;$$('[data-note-id]').forEach(x=>x.closest(".note-list-item")?.classList.toggle("active",Number(x.dataset.noteId)===item.id));R.setAssistantContext();}
  function newNote(){state.currentNote=null;const form=$("#note-form");form.reset();form.elements.id.value="";form.elements.row_version.value="";form.elements.kind.value=noteKind||"general";$("#note-save-state").textContent="新笔记尚未保存";form.elements.title.focus();R.setAssistantContext();}
  async function saveNote(event){event.preventDefault();const form=event.currentTarget,payload=Object.fromEntries(new FormData(form));if(!payload.id)delete payload.id;const version=payload.row_version?Number(payload.row_version):undefined;delete payload.row_version;try{const saved=await invoke("note.save",payload,version);state.currentNote=saved;form.elements.id.value=saved.id;form.elements.row_version.value=saved.row_version;$("#note-save-state").textContent="已保存";await notes();R.setAssistantContext();toast("笔记已保存");}catch(error){toast(error.message);}}
  async function noteBulk(action){const ids=[...noteSelection];if(!ids.length)return;const payload={ids,action};if(action==="trash"){if(!await R.confirmAction("移入回收站",`将 ${ids.length} 篇笔记移入回收站？`))return;}else{const value=await chooseValue("批量调整所属项目",[["","未分类"],...state.projects.map(item=>[String(item.id),item.title])]);if(value===null)return;payload.action="project";payload.value=value?Number(value):null;}await invoke("note.bulk",payload);noteSelection.clear();await notes();toast("批量操作已完成");}

  async function files(){const result=await invoke("library.list",{pagination:true,page:filePage,page_size:filePageSize,search:$("#file-search").value.trim(),storage_mode:$("#file-mode").value});const items=result.items;$("#file-count").textContent=`${result.pagination.total} 个文件`;$("#file-list").innerHTML=items.length?items.map(item=>`<tr><td><span class="record-cell"><i data-lucide="${fileIcon(item.kind)}"></i>${escapeHtml(item.display_name)}</span></td><td>${fileKind(item.kind)}</td><td>${storageLabel(item.storage_mode)}</td><td title="${escapeHtml(item.path)}">${escapeHtml(item.path||"—")}</td><td>${R.formatBytes(item.size_bytes)}</td><td>${statusBadge(item.link_status)}</td><td><div class="row-actions"><button class="icon-button" data-verify-file="${item.id}" title="校验完整性"><i data-lucide="shield-check"></i></button><button class="icon-button subtle" data-trash-file="${item.id}" title="移入回收站"><i data-lucide="ellipsis"></i></button></div></td></tr>`).join(""):emptyRow(7,"尚无文件。导入托管副本或链接外部路径。");let pager=$("#file-pagination");if(!pager){pager=document.createElement("footer");pager.id="file-pagination";pager.className="list-pagination";$("#file-list").closest(".panel")?.append(pager);}renderPagination(pager,{items,total:result.pagination.total,pages:result.pagination.pages,page:result.pagination.page,pageSize:result.pagination.page_size},value=>{filePage=value;files();},value=>{filePageSize=value;filePage=1;files();});icons();}
  function fileIcon(kind){return {image:"image",spreadsheet:"sheet",protocol:"clipboard-list",report:"file-chart-column",literature:"book-open",raw_data:"database"}[kind]||"file";}
  function fileKind(kind){return {image:"图像",spreadsheet:"表格",protocol:"方案",report:"报告",literature:"文献",raw_data:"原始数据",other:"其他"}[kind]||kind;}
  function storageLabel(mode){return {managed:"托管副本",external:"外部链接",zotero:"Zotero"}[mode]||mode;}
  async function beginFileImport(recordId=null){const paths=await nativeDialog("dialog.open_file",{kind:"any",multiple:false});if(!paths.length)return;fileImportRecordId=recordId;const path=paths[0],name=path.split(/[\\/]/).pop(),form=$("#file-import-form");form.reset();form.elements.path.value=path;form.elements.display_name.value=name;$("#file-selected-name").textContent=name;R.openDialog("file-dialog");}
  async function importFile(event){event.preventDefault();const form=event.currentTarget,payload=Object.fromEntries(new FormData(form));if(fileImportRecordId)payload.record_id=fileImportRecordId;try{const saved=await invoke("library.import",payload);form.closest("dialog").close();toast(saved.duplicate_count?`文件已导入，发现 ${saved.duplicate_count} 个相同内容文件`:"文件已导入");if(state.view==="record-files")await navigate("record-files",{id:fileImportRecordId},{push:false});else await files();}catch(error){$(".form-error",form).textContent=error.message;}}

  function renderLiteratureRelations(item){
    const root=$("#literature-detail");if(!root||!item)return;
    if(root.querySelector(".relation-list"))return;
    const actions=root.querySelector(".detail-actions");if(actions&&item.doi&&!actions.querySelector("[data-open-doi]")){const button=document.createElement("button");button.type="button";button.className="button compact";button.dataset.openDoi=item.doi;button.innerHTML='<i data-lucide="external-link"></i>打开 DOI';actions.prepend(button);}
    const section=[...root.querySelectorAll("section")].at(-1);if(!section)return;
    const rows=[];
    (item.projects||[]).forEach(value=>rows.push(`<article class="relation-row"><button data-open-related-project="${value.id}"><i data-lucide="folder"></i><span><b>${escapeHtml(value.title)}</b><small>项目</small></span></button><button class="icon-button" data-unlink-literature="project" data-related-id="${value.id}" title="解除项目关联"><i data-lucide="unlink"></i></button></article>`));
    (item.records||[]).forEach(value=>rows.push(`<article class="relation-row"><button data-open-related-record="${value.id}"><i data-lucide="flask-conical"></i><span><b>${escapeHtml(value.title)}</b><small>实验记录</small></span></button><button class="icon-button" data-unlink-literature="record" data-related-id="${value.id}" title="解除记录关联"><i data-lucide="unlink"></i></button></article>`));
    (item.notes||[]).forEach(value=>rows.push(`<article class="relation-row"><button data-open-related-note="${value.id}"><i data-lucide="notebook-pen"></i><span><b>${escapeHtml(value.title)}</b><small>笔记</small></span></button></article>`));
    (item.attachments||[]).forEach(value=>rows.push(`<article class="relation-row"><button data-open-library="${value.id}" title="打开 PDF 或附件"><i data-lucide="file-text"></i><span><b>${escapeHtml(value.display_name)}</b><small>打开 PDF/附件 · ${escapeHtml(value.link_status||value.storage_mode||"附件")}</small></span></button>${value.zotero_select_url?`<button class="icon-button" data-open-url="${escapeHtml(value.zotero_select_url)}" title="在 Zotero 中打开"><i data-lucide="external-link"></i></button>`:""}</article>`));
    const linker=section.querySelector(".inline-linker")?.outerHTML||"";
    section.innerHTML=`<h3>关联脉络</h3><div class="relation-list">${rows.join("")||'<p class="muted">尚未建立项目、实验记录、笔记或附件关联</p>'}</div>${linker}`;icons();
  }

  async function literatureBulkFast(action){
    const ids=[...literatureSelection];if(!ids.length)return;
    const payload={ids};
    if(action==="trash"){if(!await R.confirmAction("移入回收站",`将 ${ids.length} 篇文献移入回收站？`))return;payload.action="trash";}
    else if(action==="status"){const value=await chooseValue("批量修改阅读状态",[["unread","未读"],["reading","阅读中"],["read","已读"]]);if(value===null)return;Object.assign(payload,{action:"status",value});}
    else{const value=await chooseValue("批量关联项目",state.projects.map(item=>[String(item.id),item.title]));if(value===null)return;Object.assign(payload,{action:"project",value:Number(value)});}
    const result=await invoke("literature.bulk",payload);literatureSelection.clear();
    if(action==="trash"&&state.currentLiterature&&ids.includes(state.currentLiterature.id)){state.currentLiterature=null;$("#literature-detail").innerHTML=`<div class="empty-state"><i data-lucide="book-open"></i><p>选择一篇文献查看详情与关联脉络</p></div>`;}
    await literature();toast(`批量操作已完成：${result.updated||ids.length} 篇`);
  }

  const literatureDetailRoot=$("#literature-detail");
  if(literatureDetailRoot)new MutationObserver(()=>{if(state.currentLiterature&&!literatureDetailRoot.querySelector(".relation-list"))renderLiteratureRelations(state.currentLiterature);}).observe(literatureDetailRoot,{childList:true,subtree:true});
  const fileListRoot=$("#file-list");
  if(fileListRoot)new MutationObserver(()=>{let changed=false;fileListRoot.querySelectorAll("[data-verify-file]").forEach(verify=>{if(verify.parentElement.querySelector("[data-open-library]"))return;const open=document.createElement("button");open.type="button";open.className="icon-button";open.dataset.openLibrary=verify.dataset.verifyFile;open.title="打开文件";open.setAttribute("aria-label","打开文件");open.innerHTML='<i data-lucide="external-link"></i>';verify.before(open);changed=true;});if(changed)icons();}).observe(fileListRoot,{childList:true,subtree:true});

  let activeZoteroJob="";
  async function runZoteroSyncJob(){
    const button=$("#zotero-sync");
    if(activeZoteroJob){await invoke("zotero.sync.cancel",{job_id:activeZoteroJob});button.textContent="正在取消…";return;}
    const started=await invoke("zotero.sync.start",{});activeZoteroJob=started.job_id;button.textContent="取消同步";button.setAttribute("aria-busy","true");
    try{while(activeZoteroJob){await new Promise(resolve=>setTimeout(resolve,350));const status=await invoke("zotero.sync.status",{job_id:activeZoteroJob});$("#zotero-state").textContent=`${status.stage||"同步中"}${Number.isFinite(status.progress)?` ${status.progress}%`:""}`;if(["completed","cancelled","failed"].includes(status.state)){const result=status.result||{};toast(result.cancelled?"Zotero 同步已取消":result.error||result.collection_error||`Zotero 同步完成：新增 ${result.added||0}，更新 ${result.updated||0}，附件 ${result.attachments||0}`);activeZoteroJob="";literaturePage=1;await literature();}}}
    finally{button.removeAttribute("aria-busy");button.innerHTML='<i data-lucide="refresh-cw"></i>同步 Zotero';icons();}
  }
  $("#zotero-sync")?.addEventListener("click",event=>{event.stopImmediatePropagation();runZoteroSyncJob().catch(error=>{activeZoteroJob="";toast(error.message);});},{capture:true});

  document.addEventListener("click",async event=>{
    if(event.target.closest("#literature-collection-map")){const collectionId=Number($("#literature-collection-filter")?.value);if(!collectionId)return toast("请先选择一个 Zotero Collection");const projectId=await chooseValue("映射 Collection 到项目",state.projects.map(item=>[String(item.id),item.title]));if(projectId!==null){await invoke("zotero.collections.map",{collection_id:collectionId,project_id:Number(projectId),enabled:true});toast("Collection 已映射到项目");}return;}
    const doi=event.target.closest("[data-open-doi]");if(doi){await invoke("shell.open_external",{url:`https://doi.org/${encodeURIComponent(doi.dataset.openDoi)}`});return;}
    const openLibrary=event.target.closest("[data-open-library]");if(openLibrary){try{await invoke("library.open",{id:Number(openLibrary.dataset.openLibrary)});}catch(error){const zoteroFallback=openLibrary.closest(".relation-row")?.querySelector("[data-open-url]")?.dataset.openUrl;if(zoteroFallback){await invoke("shell.open_external",{url:zoteroFallback});toast("本地附件无法直接打开，已转到 Zotero");}else toast(error.message);}return;}
    const relatedProject=event.target.closest("[data-open-related-project]");if(relatedProject){R.go("projects",{id:Number(relatedProject.dataset.openRelatedProject)});return;}
    const relatedRecord=event.target.closest("[data-open-related-record]");if(relatedRecord){R.go("record-edit",{id:Number(relatedRecord.dataset.openRelatedRecord)});return;}
    const relatedNote=event.target.closest("[data-open-related-note]");if(relatedNote){R.go("notes",{id:Number(relatedNote.dataset.openRelatedNote)});return;}
    const relatedFile=event.target.closest("[data-open-related-file]");if(relatedFile){R.go("files",{id:Number(relatedFile.dataset.openRelatedFile)});return;}
    const unlink=event.target.closest("[data-unlink-literature]");if(unlink&&state.currentLiterature){const kind=unlink.dataset.unlinkLiterature,id=Number(unlink.dataset.relatedId);if(await R.confirmAction("解除关联",`确认解除这条${kind==="project"?"项目":"实验记录"}关联？`)){await invoke("literature.unlink",{literature_id:state.currentLiterature.id,relation_type:kind,target_id:id});await showLiterature(state.currentLiterature.id);toast("关联已解除");}return;}
    const source=event.target.closest("[data-literature-source]");if(source){literatureSource=source.dataset.literatureSource;literaturePage=1;$$('[data-literature-source]').forEach(x=>x.classList.toggle("active",x===source));await literature();return;}
    if(event.target.closest("#literature-detail-toggle")){const workspace=$(".literature-workspace"),expanded=workspace.classList.toggle("detail-expanded"),button=$("#literature-detail-toggle"),icon=$("i",button);button.title=expanded?"折叠文献详情":"展开文献详情";icon.setAttribute("data-lucide",expanded?"panel-right-close":"panel-right-open");icons();return;}
    const projectRail=event.target.closest("[data-literature-project-rail]");if(projectRail){$("#literature-project-filter").value=projectRail.dataset.literatureProjectRail;literaturePage=1;await literature();return;}
    const readStatus=event.target.closest("[data-literature-read-status]");if(readStatus){const value=readStatus.dataset.literatureReadStatus;$("#literature-status").value=$("#literature-status").value===value?"":value;literaturePage=1;$$('[data-literature-read-status]').forEach(x=>x.classList.toggle("active",x.dataset.literatureReadStatus===$("#literature-status").value));await literature();return;}
    const litTrash=event.target.closest("[data-literature-trash]");if(litTrash){await trashLiterature(Number(litTrash.dataset.literatureTrash),state.currentLiterature?.title);return;}
    const lit=event.target.closest("[data-literature-id]");if(lit){await showLiterature(Number(lit.dataset.literatureId));return;}
    const litSelect=event.target.closest("[data-literature-select]");if(litSelect){const id=Number(litSelect.dataset.literatureSelect);litSelect.checked?literatureSelection.add(id):literatureSelection.delete(id);syncBulkBar("#literature-bulk-bar",literatureSelection,literatureItems.length);return;}
    const litBulk=event.target.closest("[data-literature-bulk]");if(litBulk){await literatureBulkFast(litBulk.dataset.literatureBulk);return;}
    if(event.target.closest("[data-literature-clear]")){literatureSelection.clear();await literature();return;}if(event.target.closest("[data-literature-select-all]")){literatureItems.forEach(x=>literatureSelection.add(x.id));await literature();return;}
    const link=event.target.closest("[data-link-literature]");if(link){const projectId=$("#literature-project-link").value;if(!projectId)return toast("请选择项目");await invoke("literature.link",{literature_id:Number(link.dataset.linkLiterature),project_id:Number(projectId)});await showLiterature(Number(link.dataset.linkLiterature));toast("已关联项目");return;}
    const openUrl=event.target.closest("[data-open-url]");if(openUrl){event.preventDefault();await invoke("shell.open_external",{url:openUrl.dataset.openUrl});return;}
    const kind=event.target.closest("[data-note-kind]");if(kind){noteKind=kind.dataset.noteKind;notePage=1;$$('[data-note-kind]').forEach(x=>x.classList.toggle("active",x===kind));await notes();return;}
    const note=event.target.closest("[data-note-id]");if(note){await showNote(Number(note.dataset.noteId));return;}
    const noteSelect=event.target.closest("[data-note-select]");if(noteSelect){const id=Number(noteSelect.dataset.noteSelect);noteSelect.checked?noteSelection.add(id):noteSelection.delete(id);syncBulkBar("#note-bulk-bar",noteSelection,noteItems.length);return;}
    const noteBulkButton=event.target.closest("[data-note-bulk]");if(noteBulkButton){await noteBulk(noteBulkButton.dataset.noteBulk);return;}
    if(event.target.closest("[data-note-clear]")){noteSelection.clear();await notes();return;}if(event.target.closest("[data-note-select-all]")){noteItems.forEach(x=>noteSelection.add(x.id));await notes();return;}
    const verify=event.target.closest("[data-verify-file]");if(verify){const result=await invoke("library.verify",{id:Number(verify.dataset.verifyFile)});toast(result.link_status==="available"?"文件完整性正常":`文件状态：${result.link_status}`);await files();return;}
    const trash=event.target.closest("[data-trash-file]");if(trash&&await R.confirmAction("移入回收站","只移动文件索引，不删除外部原文件。")){await invoke("trash.move",{entity_type:"library_item",id:Number(trash.dataset.trashFile)});toast("文件索引已移入回收站");await files();}
  });
  document.addEventListener("change",async event=>{if(event.target.matches("[data-literature-check-page]")){paginate(literatureItems,literaturePage,literaturePageSize).items.forEach(item=>event.target.checked?literatureSelection.add(item.id):literatureSelection.delete(item.id));await literature();}if(event.target.matches("[data-note-check-page]")){paginate(noteItems,notePage,notePageSize).items.forEach(item=>event.target.checked?noteSelection.add(item.id):noteSelection.delete(item.id));await notes();}});
  $("#literature-form").addEventListener("submit",saveLiterature);$("#literature-query").addEventListener("click",()=>{literaturePage=1;literature();});$("#literature-search").addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();literaturePage=1;literature();}});$("#zotero-sync").addEventListener("click",async()=>{const result=await invoke("zotero.sync",{});toast(result.error||`Zotero 同步完成：新增 ${result.added}，恢复 ${result.restored||0}，更新 ${result.updated}，源端缺失 ${result.missing||0}`);literaturePage=1;await literature();});
  $("#new-note").addEventListener("click",newNote);$("#note-form").addEventListener("submit",saveNote);$("#note-query").addEventListener("click",()=>{notePage=1;notes();});$("#import-file").addEventListener("click",()=>beginFileImport());$("#record-file-import")?.addEventListener("click",()=>beginFileImport(state.currentRecord?.id));$("#file-import-form").addEventListener("submit",importFile);$("#file-search").addEventListener("input",()=>{clearTimeout(state.fileTimer);state.fileTimer=setTimeout(files,180);});$("#file-mode").addEventListener("change",files);
  R.register("literature",{load:async params=>{await literature();if(params?.id)await showLiterature(Number(params.id));}});R.register("notes",{load:async params=>{await notes();if(params?.id)await showNote(Number(params.id));},save:()=>$("#note-form").requestSubmit()});R.register("files",{load:async params=>{await files();if(params?.id){const catalog=await invoke("library.list",{}),target=catalog.find(item=>item.id===Number(params.id));if(target){$("#file-search").value=target.display_name;$("#file-mode").value="";await files();const visible=await invoke("library.list",{search:target.display_name,storage_mode:""}),index=visible.findIndex(item=>item.id===target.id),row=$$("#file-list tr")[index];row?.classList.add("selected");row?.scrollIntoView({block:"center"});}}}});
})();
