(() => {
  "use strict";
  const R=window.RLab,{$,$$,state,invoke,icons,toast,escapeHtml,dateLabel,statusBadge,nativeDialog,paginate,renderPagination,navigate}=R;
  let taskScope="all",taskMode="list",taskPage=1,taskPageSize=20,taskItems=[],taskFiltered=[];
  let calendarCursor=new Date(),calendarEvents=new Map();
  let weeklyCursor=new Date(),weeklyItems=[],weeklyPage=1,weeklyPageSize=20,currentWeeklyDetail=null;
  const taskSelection=new Set(),weeklySelection=new Set();
  $("[data-task-select-all]")?.replaceChildren("选择当前页");
  $("[data-weekly-select-all]")?.replaceChildren("选择当前页");

  function localDate(value){return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;}
  function projectName(id){return state.projects.find(item=>item.id===Number(id))?.title||"未关联项目";}
  function dueClass(deadline){if(!deadline)return "";const today=localDate(new Date()),week=new Date();week.setDate(week.getDate()+7);if(deadline<today)return "overdue";if(deadline===today)return "due-today";if(deadline<=localDate(week))return "due-week";return "";}
  function syncBulkBar(id,selection,total){const bar=$(id);bar.hidden=!selection.size;if(!bar.hidden){$("[data-selected-count]",bar).textContent=selection.size;const strong=$("strong",bar);strong.title=selection.size===total&&total>0?`已选择当前筛选的 ${total} 项`:"跨页选择会在翻页后保留";}}

  function taskPayload(){return {scope:taskScope,search:$("#task-search").value.trim(),project_id:$("#task-project-filter").value||null,status:$("#task-status-filter").value,date_start:$("#task-date-start").value,date_end:$("#task-date-end").value};}
  async function tasks(params={}){
    if(params.id){taskScope="all";for(const id of ["task-search","task-project-filter","task-status-filter","task-date-start","task-date-end"])$("#"+id).value="";$$("[data-task-scope]").forEach(item=>item.classList.toggle("active",item.dataset.taskScope==="all"));}
    const paged=taskMode==="list"&&!params.id;const result=await invoke("task.list",{...taskPayload(),...(paged?{pagination:true,page:taskPage,page_size:taskPageSize}:{})});taskItems=paged?result.items:result;if(paged)taskItems.serverPagination=result.pagination;taskFiltered=taskItems;
    const requestedTask=taskItems.find(item=>item.id===Number(params.id));if(requestedTask){state.currentTask=requestedTask;taskPage=Math.floor(taskItems.indexOf(requestedTask)/taskPageSize)+1;}
    const page=paginate(taskFiltered,taskPage,taskPageSize);taskPage=page.page;
    const surface=$("#task-list");surface.classList.toggle("board-mode",taskMode==="board");
    if(taskMode==="list"){
      surface.innerHTML=page.items.length?`<div class="task-table"><div class="task-row task-table-head"><label><input type="checkbox" data-task-check-page ${page.items.every(item=>taskSelection.has(item.id))?"checked":""}><span class="sr-only">选择当前页</span></label><span>任务</span><span>优先级</span><span>截止日期</span><span>状态</span><span></span></div>${page.items.map(item=>`<article class="task-row ${state.currentTask?.id===item.id?"selected":""}" data-select-task="${item.id}"><label class="row-selector"><input type="checkbox" data-task-select="${item.id}" ${taskSelection.has(item.id)?"checked":""}><span class="sr-only">选择 ${escapeHtml(item.title)}</span></label><button class="task-check ${item.status==="done"?"checked":""}" data-toggle-task="${item.id}" data-version="${item.row_version}" data-status="${item.status}" title="切换完成状态"><i data-lucide="check"></i></button><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(projectName(item.project_id))} · ${escapeHtml(item.notes||"无备注")}</small></span><span class="priority ${item.priority}">${{low:"低",medium:"中",high:"高"}[item.priority]||item.priority}</span><time class="${dueClass(item.deadline)}">${dateLabel(item.deadline)}</time>${statusBadge(item.status)}<button class="icon-button subtle" data-task-menu="${item.id}" title="更多操作"><i data-lucide="ellipsis"></i></button></article>`).join("")}</div>`:`<div class="empty-state"><i data-lucide="list-checks"></i><p>没有匹配的任务</p></div>`;
    }else{
      const groups=[["todo","待办"],["doing","进行中"],["blocked","受阻"],["done","已完成"]];
      surface.innerHTML=`<div class="task-board">${groups.map(([status,label])=>`<section><header><h2>${label}</h2><span>${taskFiltered.filter(x=>x.status===status).length}</span></header>${taskFiltered.filter(x=>x.status===status).map(item=>`<article data-select-task="${item.id}" class="${state.currentTask?.id===item.id?"selected":""}"><b>${escapeHtml(item.title)}</b><small>${escapeHtml(projectName(item.project_id))} · ${dateLabel(item.deadline)}</small><span class="priority ${item.priority}">${item.priority}</span></article>`).join("")||`<p class="muted">暂无任务</p>`}</section>`).join("")}</div>`;
    }
    const selectedTask=requestedTask||taskItems.find(item=>item.id===state.currentTask?.id);if(selectedTask)state.currentTask=selectedTask;if(requestedTask)surface.querySelector(`[data-select-task="${requestedTask.id}"]`)?.scrollIntoView({block:"center"});renderPagination($("#task-pagination"),page,value=>{taskPage=value;tasks();},value=>{taskPageSize=value;taskPage=1;tasks();});syncBulkBar("#task-bulk-bar",taskSelection,page.total);R.setAssistantContext();icons();
  }
  async function saveTask(event){event.preventDefault();const form=event.currentTarget;try{const payload=Object.fromEntries(new FormData(form));payload.status="todo";const saved=await invoke("task.save",payload);state.currentTask=saved;form.closest("dialog").close();form.reset();await tasks();R.setAssistantContext();toast("任务已创建");}catch(error){$(".form-error",form).textContent=error.message;}}
  async function toggleTask(button){const existing=taskItems.find(x=>x.id===Number(button.dataset.toggleTask));if(!existing)return;state.currentTask=await invoke("task.save",{...existing,status:existing.status==="done"?"todo":"done"},existing.row_version);await tasks();R.setAssistantContext();}
  function selectTask(id){const item=taskItems.find(x=>x.id===id);if(!item)return;state.currentTask=item;R.setAssistantContext();tasks();}
  function updateTaskSelection(input){const id=Number(input.dataset.taskSelect);input.checked?taskSelection.add(id):taskSelection.delete(id);syncBulkBar("#task-bulk-bar",taskSelection,taskFiltered.length);}
  async function chooseBulkValue(title,kind,options=[]){
    const trigger=document.activeElement;
    const dialog=document.createElement("dialog"),control=kind==="date"?`<input name="value" type="date" required>`:`<select name="value">${options.map(([value,label])=>`<option value="${escapeHtml(value)}">${escapeHtml(label)}</option>`).join("")}</select>`;
    dialog.innerHTML=`<form method="dialog"><header><div><h2>${escapeHtml(title)}</h2></div></header><label>新值${control}</label><footer><button class="button" value="cancel">取消</button><button class="button primary" value="apply">应用</button></footer></form>`;document.body.append(dialog);dialog.showModal();return new Promise(resolve=>dialog.addEventListener("close",()=>{const value=dialog.returnValue==="apply"?new FormData($("form",dialog)).get("value"):null;dialog.remove();trigger?.focus?.();resolve(value);},{once:true}));
  }
  function monthBounds(cursor){const start=new Date(cursor.getFullYear(),cursor.getMonth(),1),mondayOffset=(start.getDay()+6)%7,gridStart=new Date(start);gridStart.setDate(start.getDate()-mondayOffset);const gridEnd=new Date(gridStart);gridEnd.setDate(gridStart.getDate()+41);return {start,gridStart,gridEnd};}
  function syncCalendarSelectors(){const year=$("#calendar-year"),month=$("#calendar-month"),current=calendarCursor.getFullYear(),years=[];for(let value=current-15;value<=current+15;value++)years.push(`<option value="${value}" ${value===current?"selected":""}>${value} 年</option>`);year.innerHTML=years.join("");month.innerHTML=Array.from({length:12},(_,index)=>`<option value="${index}" ${index===calendarCursor.getMonth()?"selected":""}>${index+1} 月</option>`).join("");}
  function calendarIcon(type){return {experiment:"flask-conical",task:"circle-check",weekly:"presentation",meeting:"users",reminder:"bell"}[type]||"calendar";}
  async function openCalendarSource(item){if(!item)return;if(item.source_type==="record")return navigate("record-edit",{id:Number(item.source_id)});if(item.source_type==="task"){await navigate("tasks");selectTask(Number(item.source_id));return;}if(item.source_type==="weekly"){await navigate("weekly-library");await showWeeklyDetail(Number(item.source_id));return;}if(item.source_type==="event"&&item.lab_record_id)return navigate("record-edit",{id:Number(item.lab_record_id)});if(item.project_id)return navigate("project-workbench",{id:Number(item.project_id)});}
  async function calendar(params={}){let requestedDate="";if(params?.date&&/^\d{4}-\d{2}-\d{2}$/.test(String(params.date))){const parsed=new Date(`${params.date}T12:00:00`);if(!Number.isNaN(parsed.getTime())){calendarCursor=parsed;requestedDate=String(params.date);$("#calendar-date").value=requestedDate;}}const {start,gridStart,gridEnd}=monthBounds(calendarCursor);$("#calendar-title").textContent=`${start.getFullYear()} 年 ${start.getMonth()+1} 月`;syncCalendarSelectors();const locateButton=$("#calendar-locate");if(locateButton&&!$("#calendar-clear-date")){const clear=document.createElement("button");clear.id="calendar-clear-date";clear.type="button";clear.className="button compact";clear.title="清除定位日期";clear.innerHTML='<i data-lucide="x"></i>清除定位';locateButton.insertAdjacentElement("afterend",clear);}const events=await invoke("calendar.list",{start:localDate(gridStart),end:localDate(gridEnd)});calendarEvents=new Map(events.map(item=>[item.id,item]));const selectedEvent=events.find(item=>item.source_type==="event"&&item.source_id===state.currentCalendarEvent?.id);if(selectedEvent)state.currentCalendarEvent={...selectedEvent,id:selectedEvent.source_id};const grouped=events.reduce((acc,item)=>((acc[String(item.date).slice(0,10)]??=[]).push(item),acc),{}),today=localDate(new Date());$("#calendar-grid").innerHTML=Array.from({length:42},(_,index)=>{const day=new Date(gridStart);day.setDate(gridStart.getDate()+index);const key=localDate(day),items=grouped[key]||[];return `<div class="calendar-cell ${day.getMonth()!==start.getMonth()?"outside":""} ${key===today?"today":""} ${key===requestedDate?"selected-day":""}" data-calendar-day="${key}"><button class="calendar-date" data-calendar-date="${key}" title="在 ${key} 新建事件" type="button">${day.getDate()}</button><div>${items.slice(0,4).map(item=>`<button class="calendar-event ${item.event_type}" data-calendar-event="${escapeHtml(item.id)}" title="${escapeHtml(item.title)}" type="button"><i data-lucide="${calendarIcon(item.event_type)}"></i><span>${escapeHtml(item.title)}</span></button>`).join("")}${items.length>4?`<button class="calendar-overflow" data-calendar-overflow="${key}" type="button">另有 ${items.length-4} 项</button>`:""}</div></div>`;}).join("");if(requestedDate&&grouped[requestedDate]?.length)showDayEvents(requestedDate);R.setAssistantContext();icons();}
  async function trashCalendarEvent(item){if(!item||item.source_type!=="event")return;if(!await R.confirmAction("移入回收站",`将日历事件“${item.title||"未命名事件"}”移入回收站？`))return;await invoke("trash.move",{entity_type:"calendar_event",id:Number(item.source_id)});state.currentCalendarEvent=null;$("#calendar-detail").hidden=true;await calendar();R.setAssistantContext();toast("日历事件已移入回收站");}
  function showCalendarDetail(item){if(!item)return;state.currentCalendarEvent=item.source_type==="event"?{...item,id:item.source_id}:null;if(item.source_type==="task"){const task=taskItems.find(x=>x.id===item.source_id);if(task)state.currentTask=task;}R.setAssistantContext();const detail=$("#calendar-detail");detail.hidden=false;const canTrash=item.source_type==="event"&&item.movable!==false,canOpen=item.source_type!=="event"||item.lab_record_id||item.project_id;detail.innerHTML=`<header><span class="event-type ${escapeHtml(item.event_type)}"><i data-lucide="${calendarIcon(item.event_type)}"></i>${escapeHtml({experiment:"实验",task:"任务",weekly:"周报",meeting:"会议",reminder:"提醒"}[item.event_type]||item.event_type)}</span><div class="detail-actions">${canOpen?`<button class="button compact" data-open-calendar-source="${escapeHtml(item.id)}" type="button"><i data-lucide="arrow-up-right"></i>查看内容</button>`:""}<button class="icon-button" data-close-calendar-detail title="关闭" type="button"><i data-lucide="x"></i></button>${canTrash?`<button class="icon-button subtle" data-trash-calendar-event="${item.source_id}" title="移入回收站" type="button"><i data-lucide="trash-2"></i></button>`:""}</div></header><h3>${escapeHtml(item.title)}</h3><dl><div><dt>日期与时间</dt><dd>${dateLabel(item.starts_at||item.date,true)}</dd></div><div><dt>所属项目</dt><dd>${escapeHtml(projectName(item.project_id))}</dd></div>${item.notes?`<div><dt>备注</dt><dd>${escapeHtml(item.notes)}</dd></div>`:""}</dl>`;icons();}
  function showDayEvents(key){const items=[...calendarEvents.values()].filter(item=>String(item.date).slice(0,10)===key),detail=$("#calendar-detail");detail.hidden=false;detail.innerHTML=`<header><h3>${key}</h3><button class="icon-button" data-close-calendar-detail type="button"><i data-lucide="x"></i></button></header><div class="day-event-list">${items.map(item=>`<button data-calendar-event="${escapeHtml(item.id)}" type="button"><i data-lucide="${calendarIcon(item.event_type)}"></i><span><b>${escapeHtml(item.title)}</b><small>${dateLabel(item.date,true)}</small></span></button>`).join("")}</div>`;icons();}
  function beginEventAt(key){const form=$("#event-form");form.reset();form.elements.starts_at.value=`${key}T09:00`;R.openDialog("event-dialog");}
  async function saveEvent(event){event.preventDefault();const form=event.currentTarget;try{const saved=await invoke("calendar.create",Object.fromEntries(new FormData(form)));state.currentCalendarEvent=saved;form.closest("dialog").close();form.reset();await calendar();R.setAssistantContext();toast("日历事件已创建");}catch(error){$(".form-error",form).textContent=error.message;}}

  async function weekly(){const data=await invoke("weekly.current",{week:localDate(weeklyCursor)});state.currentWeekly=data;$("#weekly-period").textContent=`${data.period_start} 至 ${data.period_end}`;$("#weekly-metrics").innerHTML=[["实验记录",data.counts.records],["完成任务",data.counts.tasks],["阅读文献",data.counts.literature],["笔记更新",data.counts.notes],["推进项目",data.counts.projects]].map(x=>`<div><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("");$("#weekly-sources").innerHTML=(data.entries||[]).map((item,index)=>`<label class="source-row"><input type="checkbox" data-weekly-source="${index}" ${item.include_state!=="excluded"?"checked":""}><span><b>${escapeHtml(item.source_title)}</b><small>${escapeHtml(item.source_type)} · ${dateLabel(item.source_date)}</small><p>${escapeHtml(item.source_excerpt||"无摘要")}</p></span></label>`).join("")||`<p class="muted">本周尚无可汇总来源。</p>`;const form=$("#weekly-form");form.elements.id.value=data.id||"";form.elements.row_version.value=data.row_version||0;form.elements.body.value=data.body||"";form.elements.issues_and_feedback.value=data.issues_and_feedback||"";form.elements.next_week_plan.value=data.next_week_plan||"";R.setAssistantContext();icons();}
  async function saveWeekly(){if(!state.currentWeekly)return;const form=$("#weekly-form"),payload=Object.fromEntries(new FormData(form));payload.id=payload.id?Number(payload.id):null;payload.row_version=Number(payload.row_version)||0;payload.period_start=state.currentWeekly.period_start;payload.entries=(state.currentWeekly.entries||[]).map((item,index)=>({...item,include_state:$(`[data-weekly-source="${index}"]`)?.checked?"included":"excluded"}));try{const result=await invoke("weekly.save",payload,payload.id?payload.row_version:undefined);state.currentWeekly={...state.currentWeekly,...payload,...result};form.elements.id.value=result.id;form.elements.row_version.value=result.row_version;R.setAssistantContext();toast("周报已保存");}catch(error){toast(error.message);}}
  function weeklyPayload(){return {search:$("#weekly-search").value.trim(),date_start:$("#weekly-date-start").value,date_end:$("#weekly-date-end").value,project_id:$("#weekly-project-filter").value||null,status:$("#weekly-status-filter").value};}
  function enhanceWeeklyManagementDetail(){const detail=$("#weekly-library-detail");if(!detail||!currentWeeklyDetail)return;for(const section of $$(":scope > section",detail)){const title=$("h3",section)?.textContent;if(title==="内容摘要"||title==="问题与反馈")section.remove();}const annotationSection=$$(":scope > section",detail).find(section=>$("h3",section)?.textContent==="批注、说明与指导");if(annotationSection&&!$(".annotation-compose",annotationSection)){annotationSection.insertAdjacentHTML("afterbegin",`<div class="annotation-compose"><div><select id="weekly-annotation-kind" aria-label="批注类型"><option value="批注">批注</option><option value="说明">说明</option><option value="指导">指导</option></select><select id="weekly-annotation-status" aria-label="处理状态"><option value="待处理">待处理</option><option value="已处理">已处理</option></select></div><textarea id="weekly-annotation-content" rows="3" placeholder="添加批注、说明或指导"></textarea><button class="button primary compact" type="button" data-weekly-annotation-add><i data-lucide="message-square-plus"></i>添加批注</button></div>`);icons();}}
  function enhanceWeeklyHistorySources(){const detail=$("#weekly-library-detail");if(!detail||!currentWeeklyDetail||(currentWeeklyDetail.entries||[]).length===0||$(".weekly-history-sources",detail))return;const section=document.createElement("section");section.className="weekly-history-sources";section.innerHTML=`<h3>报告来源</h3><div class="relation-list">${currentWeeklyDetail.entries.map((item,index)=>`<article class="relation-row"><button data-open-weekly-history-source="${index}"><i data-lucide="arrow-up-right"></i><span><b>${escapeHtml(item.source_title)}</b><small>${escapeHtml(item.source_type)} · ${dateLabel(item.source_date)}</small></span></button></article>`).join("")}</div>`;detail.append(section);icons();}
  const weeklyDetailObserver=new MutationObserver(()=>{enhanceWeeklyManagementDetail();enhanceWeeklyHistorySources();});weeklyDetailObserver.observe($("#weekly-library-detail"),{childList:true});const weeklySummaryField=$("#weekly-upload-form textarea[name=summary]");if(weeklySummaryField)weeklySummaryField.closest("label").hidden=true;
  async function beginWeeklyUpload(projectId=null,report=null){
    const paths=await nativeDialog("dialog.open_file",{kind:"reports",multiple:false});if(!paths.length)return;
    const path=paths[0],name=path.split(/[\\/]/).pop(),form=$("#weekly-upload-form"),today=localDate(new Date());form.reset();
    form.elements.path.value=path;form.elements.report_id.value=report?.id||"";form.elements.row_version.value=report?.row_version||"";
    form.elements.title.value=report?.title||name.replace(/\.[^.]+$/,"");form.elements.report_date.value=report?.report_date||today;
    form.elements.period_start.value=report?.period_start||"";form.elements.period_end.value=report?.period_end||"";
    form.elements.project_id.value=projectId||report?.project_id||"";form.elements.status.value=report?.status||"submitted";form.elements.summary.value=report?.summary||"";
    $("#weekly-upload-title").textContent=report?"替换周报文件":"上传周总结";$("#weekly-selected-name").textContent=report?`${name} · 将保存为新版本`:name;R.openDialog("weekly-upload-dialog");icons();
  }
  async function importWeeklyFile(event){event.preventDefault();const form=event.currentTarget,payload=Object.fromEntries(new FormData(form)),version=payload.row_version?Number(payload.row_version):undefined;if(payload.report_id)payload.report_id=Number(payload.report_id);else delete payload.report_id;delete payload.row_version;try{const saved=await invoke("weekly.import_file",payload,version);currentWeeklyDetail=saved;state.currentWeekly=saved;form.closest("dialog").close();await weeklyLibrary();toast(saved.files?.length>1?`新版本 v${saved.current_file.version_number} 已保存`:"周报文件已导入");}catch(error){$(".form-error",form).textContent=error.message;}}
  async function saveWeeklyCopy(reportId,file){const paths=await nativeDialog("dialog.save_file",{suggested_name:file.original_name||file.display_name||"weekly-report"});if(!paths.length)return;const result=await invoke("weekly.export_file",{report_id:reportId,file_id:file.id,path:paths[0]});toast(`副本已保存：${R.formatBytes(result.size_bytes)}`);}
  function showWeeklyMenu(button,item){document.querySelector(".row-actions-menu")?.remove();const menu=document.createElement("div"),rect=button.getBoundingClientRect();menu.className="row-actions-menu";menu.style.left=`${Math.max(8,rect.right-170)}px`;menu.style.top=`${Math.min(window.innerHeight-176,rect.bottom+4)}px`;menu.innerHTML=`<button data-weekly-row-action="open" data-report-id="${item.id}"><i data-lucide="folder-open"></i>打开当前文件</button><button data-weekly-row-action="save" data-report-id="${item.id}"><i data-lucide="download"></i>另存副本</button><button data-weekly-row-action="replace" data-report-id="${item.id}"><i data-lucide="replace"></i>替换为新版本</button><button data-weekly-row-action="trash" data-report-id="${item.id}"><i data-lucide="trash-2"></i>移入回收站</button>`;document.body.append(menu);icons();setTimeout(()=>document.addEventListener("click",event=>{if(!event.target.closest(".row-actions-menu"))menu.remove();},{once:true}),0);}
  function weeklyFileType(item){const name=item.original_name||"";return name.includes(".")?name.split(".").pop().toUpperCase():"文件";}
  async function weeklyLibrary(){const [filtered,catalog]=await Promise.all([invoke("weekly.list",weeklyPayload()),invoke("weekly.list",{})]);weeklyItems=filtered;$("#weekly-total-count").textContent=catalog.length;const selectedProject=$("#weekly-project-filter").value;$("#weekly-project-rail").innerHTML=`<button data-weekly-rail-project="" class="${!selectedProject?"active":""}"><i data-lucide="folders"></i><span>全部项目</span></button>${state.projects.map(project=>`<button data-weekly-rail-project="${project.id}" class="${selectedProject===String(project.id)?"active":""}"><i data-lucide="folder"></i><span>${escapeHtml(project.title)}</span></button>`).join("")}`;const page=paginate(weeklyItems,weeklyPage,weeklyPageSize);weeklyPage=page.page;$("#weekly-library-list").innerHTML=page.items.length?`<div class="resource-table weekly-table"><div class="resource-table-head weekly-table-head"><label><input type="checkbox" data-weekly-check-page ${page.items.every(item=>weeklySelection.has(item.id))?"checked":""} aria-label="选择当前页"></label><span>周报名称</span><span>日期</span><span>项目</span><span>状态</span><span>文件类型</span><span>批注</span><span>更新时间</span><span></span></div>${page.items.map(item=>`<article class="resource-table-row weekly-table-row ${currentWeeklyDetail?.id===item.id?"active":""}"><label class="row-selector"><input type="checkbox" data-weekly-select="${item.id}" ${weeklySelection.has(item.id)?"checked":""} aria-label="选择 ${escapeHtml(item.title)}"></label><button data-weekly-report="${item.id}" title="查看 ${escapeHtml(item.title)}"><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.summary||"无摘要")}</small></span><span>${dateLabel(item.report_date)}</span><span>${escapeHtml(projectName(item.project_id))}</span>${statusBadge(item.status)}<span>${escapeHtml(weeklyFileType(item))}</span><span>${item.annotation_count||0}</span><span>${dateLabel(item.updated_at,true)}</span></button><button class="icon-button subtle" data-weekly-menu="${item.id}" title="更多操作"><i data-lucide="ellipsis"></i></button></article>`).join("")}</div>`:`<div class="empty-state"><i data-lucide="archive"></i><p>没有匹配的周报</p></div>`;renderPagination($("#weekly-pagination"),page,value=>{weeklyPage=value;weeklyLibrary();},value=>{weeklyPageSize=value;weeklyPage=1;weeklyLibrary();});syncBulkBar("#weekly-bulk-bar",weeklySelection,weeklyItems.length);if(currentWeeklyDetail&&!weeklyItems.some(x=>x.id===currentWeeklyDetail.id))currentWeeklyDetail=null;if(currentWeeklyDetail)await showWeeklyDetail(currentWeeklyDetail.id);else if(page.items[0])await showWeeklyDetail(page.items[0].id);icons();}

  async function weeklyLibraryPaged(){
    const [result,catalog]=await Promise.all([
      invoke("weekly.list",{...weeklyPayload(),pagination:true,page:weeklyPage,page_size:weeklyPageSize}),
      invoke("weekly.list",{pagination:true,page:1,page_size:1}),
    ]);
    weeklyItems=result.items;weeklyItems.serverPagination=result.pagination;$("#weekly-total-count").textContent=catalog.pagination.total;
    const selectedProject=$("#weekly-project-filter").value;
    $("#weekly-project-rail").innerHTML=`<button data-weekly-rail-project="" class="${!selectedProject?"active":""}"><i data-lucide="folders"></i><span>全部项目</span></button>${state.projects.map(project=>`<button data-weekly-rail-project="${project.id}" class="${selectedProject===String(project.id)?"active":""}"><i data-lucide="folder"></i><span>${escapeHtml(project.title)}</span></button>`).join("")}`;
    const page=paginate(weeklyItems,weeklyPage,weeklyPageSize);weeklyPage=page.page;
    $("#weekly-library-list").innerHTML=page.items.length?`<div class="resource-table weekly-table"><div class="resource-table-head weekly-table-head"><label><input type="checkbox" data-weekly-check-page ${page.items.every(item=>weeklySelection.has(item.id))?"checked":""} aria-label="选择当前页"></label><span>周报名称</span><span>日期</span><span>项目</span><span>状态</span><span>文件类型</span><span>批注</span><span>更新时间</span><span></span></div>${page.items.map(item=>`<article class="resource-table-row weekly-table-row ${currentWeeklyDetail?.id===item.id?"active":""}"><label class="row-selector"><input type="checkbox" data-weekly-select="${item.id}" ${weeklySelection.has(item.id)?"checked":""} aria-label="选择 ${escapeHtml(item.title)}"></label><button data-weekly-report="${item.id}" title="查看 ${escapeHtml(item.title)}"><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.summary||"无摘要")}</small></span><span>${dateLabel(item.report_date)}</span><span>${escapeHtml(projectName(item.project_id))}</span>${statusBadge(item.status)}<span>${escapeHtml(weeklyFileType(item))}</span><span>${item.annotation_count||0}</span><span>${dateLabel(item.updated_at,true)}</span></button><button class="icon-button subtle" data-weekly-menu="${item.id}" title="更多操作"><i data-lucide="ellipsis"></i></button></article>`).join("")}</div>`:`<div class="empty-state"><i data-lucide="archive"></i><p>没有匹配的周报</p></div>`;
    renderPagination($("#weekly-pagination"),page,value=>{weeklyPage=value;weeklyLibrary();},value=>{weeklyPageSize=value;weeklyPage=1;weeklyLibrary();});syncBulkBar("#weekly-bulk-bar",weeklySelection,page.total);
    if(currentWeeklyDetail&&weeklyItems.some(x=>x.id===currentWeeklyDetail.id))await showWeeklyDetail(currentWeeklyDetail.id);else if(page.items[0])await showWeeklyDetail(page.items[0].id);else currentWeeklyDetail=null;icons();
  }
  weeklyLibrary=weeklyLibraryPaged;
  async function showWeeklyDetail(id){const item=await invoke("weekly.get",{id});currentWeeklyDetail=item;state.currentWeekly=item;R.setAssistantContext();const files=item.files||[],current=item.current_file;$("#weekly-library-detail").innerHTML=`<header class="detail-header"><span class="eyebrow">${dateLabel(item.report_date)}</span><h2>${escapeHtml(item.title)}</h2><p>${item.period_start||"—"} 至 ${item.period_end||"—"}</p><div class="weekly-detail-actions">${current?`<button class="button compact" data-weekly-file-open="${current.id}"><i data-lucide="external-link"></i>打开文件</button><button class="button compact" data-weekly-file-save="${current.id}"><i data-lucide="download"></i>另存副本</button>`:""}<button class="button compact" data-weekly-replace="${item.id}"><i data-lucide="replace"></i>${current?"上传新版本":"添加文件"}</button><button class="button compact" data-weekly-report-directory="${item.id}"><i data-lucide="folder-open"></i>打开目录</button></div></header><section><h3>周报信息</h3><dl class="detail-metadata"><dt>所属项目</dt><dd>${escapeHtml(projectName(item.project_id))}</dd><dt>状态</dt><dd>${statusBadge(item.status)}</dd><dt>报告日期</dt><dd>${dateLabel(item.report_date)}</dd><dt>当前文件</dt><dd>${escapeHtml(current?.original_name||"尚未上传")}</dd><dt>文件大小</dt><dd>${current?R.formatBytes(current.size_bytes):"—"}</dd><dt>更新时间</dt><dd>${dateLabel(item.updated_at,true)}</dd></dl></section><section><h3>内容摘要</h3><p>${escapeHtml(item.summary||"尚无摘要")}</p></section><section><h3>文件版本</h3><div class="weekly-file-versions">${files.map(file=>`<article><span><b>v${file.version_number} · ${escapeHtml(file.original_name)}</b><small>${escapeHtml(file.storage_mode==="managed"?"托管副本":"外部链接")} · ${R.formatBytes(file.size_bytes)} · ${dateLabel(file.updated_at,true)}</small></span><button class="icon-button" data-weekly-file-open="${file.id}" title="打开"><i data-lucide="external-link"></i></button><button class="icon-button" data-weekly-file-save="${file.id}" title="另存副本"><i data-lucide="download"></i></button></article>`).join("")||`<p class="muted">该周报尚未关联文件</p>`}</div></section><section><h3>问题与反馈</h3><p>${escapeHtml(item.issues_and_feedback||"尚无内容")}</p></section><section><h3>批注、说明与指导</h3><div class="annotation-timeline">${(item.updates||[]).map(update=>`<article><span>${escapeHtml(update.kind)}</span><b>${escapeHtml(update.content)}</b><small>${dateLabel(update.created_at,true)} · ${escapeHtml(update.status)}</small></article>`).join("")||`<p class="muted">尚无批注</p>`}</div></section>`;$$('[data-weekly-report]').forEach(x=>x.closest(".resource-table-row")?.classList.toggle("active",Number(x.dataset.weeklyReport)===item.id));icons();}
  async function weeklyBulk(action){const ids=[...weeklySelection];if(!ids.length)return;const payload={ids,action};if(action==="trash"){if(!await R.confirmAction("移入回收站",`将 ${ids.length} 份周报移入回收站？`))return;}else{const value=await chooseBulkValue("批量编辑周报","select",[["status:draft","状态：草稿"],["status:submitted","状态：已提交"],["status:reviewed","状态：已批注"],["status:archived","状态：已归档"],...state.projects.map(x=>[`project:${x.id}`,`项目：${x.title}`])]);if(value===null)return;const [kind,raw]=value.split(":");payload.action=kind;payload.value=kind==="project"?Number(raw):raw;}await invoke("weekly.bulk",payload);weeklySelection.clear();await weeklyLibrary();toast("批量操作已完成");}

  async function ppt(){const end=new Date(),start=new Date();start.setDate(end.getDate()-6);$("#ppt-start").value=localDate(start);$("#ppt-end").value=localDate(end);await updatePptPreview();}
  async function updatePptPreview(){const records=await invoke("record.list",{project_id:$("#ppt-project").value||null}),start=$("#ppt-start").value,end=$("#ppt-end").value,filtered=records.filter(item=>(!start||!item.experiment_date||item.experiment_date>=start)&&(!end||!item.experiment_date||item.experiment_date<=end));$("#ppt-preview").innerHTML=filtered.length?`<div class="evidence-list">${filtered.map(item=>`<div><i data-lucide="flask-conical"></i><span><b>${escapeHtml(item.title)}</b><small>${dateLabel(item.experiment_date)} · ${statusBadge(item.status)}</small></span></div>`).join("")}</div>`:`<div class="empty-state"><i data-lucide="scan-search"></i><p>当前范围没有实验记录</p></div>`;icons();return filtered;}
  async function generatePpt(){const records=await updatePptPreview();if(!records.length)return toast("当前范围没有可生成内容");const paths=await nativeDialog("dialog.save_file",{suggested_name:`R-LAB-weekly-${$("#ppt-start").value}.pptx`});if(!paths.length)return;const result=await invoke("weekly.ppt",{path:paths[0],record_ids:records.map(x=>x.id),title:$("#ppt-rule").value});toast(`PPTX 已生成：${R.formatBytes(result.size_bytes)}`);}

  async function taskBulkFast(action){const ids=[...taskSelection];if(!ids.length)return;const payload={ids,action};
    if(action==="trash"){if(!await R.confirmAction("移入回收站",`将 ${ids.length} 项任务移入回收站？`))return;}
    else if(action==="status")payload.value=await chooseBulkValue("批量修改任务状态","select",[["todo","待办"],["doing","进行中"],["blocked","受阻"],["done","已完成"]]);
    else if(action==="project")payload.value=await chooseBulkValue("批量调整所属项目","select",[["","不关联项目"],...state.projects.map(x=>[String(x.id),x.title])]);
    else payload.value=await chooseBulkValue("批量修改截止日期","date");
    if(action!=="trash"&&payload.value===null)return;await invoke("task.bulk",payload);taskSelection.clear();await tasks();toast("批量操作已完成");
  }

  function enhanceWeeklySources(){
    const root=$("#weekly-sources");if(!root)return;
    root.querySelectorAll("[data-weekly-source]").forEach(input=>{const row=input.closest(".source-row"),index=Number(input.dataset.weeklySource),item=state.currentWeekly?.entries?.[index];if(!row||!item||row.dataset.jumpReady)return;row.dataset.jumpReady="true";const button=document.createElement("button");button.type="button";button.className="icon-button weekly-source-jump";button.dataset.openWeeklySource=index;button.title="打开来源";button.setAttribute("aria-label",`打开来源：${item.source_title||item.source_type}`);button.innerHTML='<i data-lucide="arrow-up-right"></i>';row.append(button);});icons();
  }
  // Observe only direct children.  Lucide replaces <i> nodes with SVGs; a
  // subtree observer would see that replacement, call icons() again, and
  // spin the UI thread indefinitely after opening the weekly view.
  const weeklySourcesRoot=$("#weekly-sources");if(weeklySourcesRoot)new MutationObserver(enhanceWeeklySources).observe(weeklySourcesRoot,{childList:true});

  document.addEventListener("click",async event=>{
    const historySource=event.target.closest("[data-open-weekly-history-source]");if(historySource){const item=currentWeeklyDetail?.entries?.[Number(historySource.dataset.openWeeklyHistorySource)];if(!item)return;if(item.source_type==="record")R.go("record-edit",{id:item.source_id});else if(item.source_type==="task")R.go("tasks",{id:item.source_id});else if(item.source_type==="literature")R.go("literature",{id:item.source_id});else if(item.source_type==="note")R.go("notes",{id:item.source_id});else toast("该来源暂不支持直接跳转");return;}
    const sourceJump=event.target.closest("[data-open-weekly-source]");if(sourceJump){event.preventDefault();const item=state.currentWeekly?.entries?.[Number(sourceJump.dataset.openWeeklySource)];if(!item)return;if(item.source_type==="record")R.go("record-edit",{id:item.source_id});else if(item.source_type==="task")R.go("tasks",{id:item.source_id});else if(item.source_type==="literature")R.go("literature",{id:item.source_id});else if(item.source_type==="note")R.go("notes",{id:item.source_id});else toast("该来源暂不支持直接跳转");return;}
    if(event.target.closest("[data-weekly-annotation-add]")){if(!currentWeeklyDetail)return;const content=$("#weekly-annotation-content").value.trim();if(!content)return toast("请输入批注内容");currentWeeklyDetail=await invoke("weekly.annotate",{id:currentWeeklyDetail.id,kind:$("#weekly-annotation-kind").value,status:$("#weekly-annotation-status").value,content},currentWeeklyDetail.row_version);state.currentWeekly=currentWeeklyDetail;await showWeeklyDetail(currentWeeklyDetail.id);toast("周报批注已添加");return;}
    const weeklyRailStatus=event.target.closest("[data-weekly-rail-status]");if(weeklyRailStatus){$("#weekly-status-filter").value=weeklyRailStatus.dataset.weeklyRailStatus;weeklyPage=1;$$('[data-weekly-rail-status]').forEach(x=>x.classList.toggle("active",x===weeklyRailStatus));await weeklyLibrary();return;}
    const weeklyRailProject=event.target.closest("[data-weekly-rail-project]");if(weeklyRailProject){$("#weekly-project-filter").value=weeklyRailProject.dataset.weeklyRailProject;weeklyPage=1;await weeklyLibrary();return;}
    const scope=event.target.closest("[data-task-scope]");if(scope){taskScope=scope.dataset.taskScope;taskPage=1;$$('[data-task-scope]').forEach(x=>x.classList.toggle("active",x===scope));await tasks();return;}
    const mode=event.target.closest("[data-task-mode]");if(mode){taskMode=mode.dataset.taskMode;$$('[data-task-mode]').forEach(x=>x.classList.toggle("active",x===mode));await tasks();return;}
    const taskSelect=event.target.closest("[data-task-select]");if(taskSelect){event.stopPropagation();updateTaskSelection(taskSelect);return;}
    const taskRow=event.target.closest("[data-select-task]");if(taskRow&&!event.target.closest("button,input,label")){selectTask(Number(taskRow.dataset.selectTask));return;}
    const toggle=event.target.closest("[data-toggle-task]");if(toggle){await toggleTask(toggle);return;}
    const taskBulkButton=event.target.closest("[data-task-bulk]");if(taskBulkButton){await taskBulkFast(taskBulkButton.dataset.taskBulk);return;}
    if(event.target.closest("[data-task-clear]")){taskSelection.clear();await tasks();return;}
    if(event.target.closest("[data-task-select-all]")){taskFiltered.forEach(x=>taskSelection.add(x.id));await tasks();return;}
    const eventButton=event.target.closest("[data-calendar-event]");if(eventButton){showCalendarDetail(calendarEvents.get(eventButton.dataset.calendarEvent));return;}
    const overflow=event.target.closest("[data-calendar-overflow]");if(overflow){showDayEvents(overflow.dataset.calendarOverflow);return;}
    const day=event.target.closest("[data-calendar-date]");if(day){beginEventAt(day.dataset.calendarDate);return;}
    const calendarTrash=event.target.closest("[data-trash-calendar-event]");if(calendarTrash){const sourceId=Number(calendarTrash.dataset.trashCalendarEvent),item=state.currentCalendarEvent?.source_type==="event"&&Number(state.currentCalendarEvent.source_id)===sourceId?state.currentCalendarEvent:calendarEvents.get(`event:${sourceId}`);await trashCalendarEvent(item);return;}
    const calendarSource=event.target.closest("[data-open-calendar-source]");if(calendarSource){await openCalendarSource(calendarEvents.get(calendarSource.dataset.openCalendarSource));return;}
    if(event.target.closest("[data-close-calendar-detail]")){state.currentCalendarEvent=null;$("#calendar-detail").hidden=true;R.setAssistantContext();return;}
    const weeklyMenu=event.target.closest("[data-weekly-menu]");if(weeklyMenu){event.stopPropagation();const item=weeklyItems.find(value=>value.id===Number(weeklyMenu.dataset.weeklyMenu));if(item)showWeeklyMenu(weeklyMenu,item);return;}
    const weeklyRowAction=event.target.closest("[data-weekly-row-action]");if(weeklyRowAction){const id=Number(weeklyRowAction.dataset.reportId),item=await invoke("weekly.get",{id}),file=item.current_file;weeklyRowAction.closest(".row-actions-menu")?.remove();if(weeklyRowAction.dataset.weeklyRowAction==="open"){if(!file)return toast("该周报尚未关联文件");await invoke("weekly.open_file",{report_id:id,file_id:file.id});}if(weeklyRowAction.dataset.weeklyRowAction==="save"){if(!file)return toast("该周报尚未关联文件");await saveWeeklyCopy(id,file);}if(weeklyRowAction.dataset.weeklyRowAction==="replace")await beginWeeklyUpload(item.project_id,item);if(weeklyRowAction.dataset.weeklyRowAction==="trash"&&await R.confirmAction("移入回收站",`将周报“${item.title}”移入回收站？`)){await invoke("trash.move",{entity_type:"weekly_report",id});currentWeeklyDetail=null;await weeklyLibrary();}return;}
    const report=event.target.closest("[data-weekly-report]");if(report){await showWeeklyDetail(Number(report.dataset.weeklyReport));return;}
    const weeklySelect=event.target.closest("[data-weekly-select]");if(weeklySelect){const id=Number(weeklySelect.dataset.weeklySelect);weeklySelect.checked?weeklySelection.add(id):weeklySelection.delete(id);syncBulkBar("#weekly-bulk-bar",weeklySelection,weeklyItems.length);return;}
    const weeklyBulkButton=event.target.closest("[data-weekly-bulk]");if(weeklyBulkButton){await weeklyBulk(weeklyBulkButton.dataset.weeklyBulk);return;}
    if(event.target.closest("[data-weekly-clear]")){weeklySelection.clear();await weeklyLibrary();return;}
    if(event.target.closest("[data-weekly-select-all]")){weeklyItems.forEach(x=>weeklySelection.add(x.id));await weeklyLibrary();return;}
    const weeklyFileOpen=event.target.closest("[data-weekly-file-open]");if(weeklyFileOpen){await invoke("weekly.open_file",{report_id:currentWeeklyDetail.id,file_id:Number(weeklyFileOpen.dataset.weeklyFileOpen)});return;}
    const weeklyFileSave=event.target.closest("[data-weekly-file-save]");if(weeklyFileSave){const file=currentWeeklyDetail.files.find(value=>value.id===Number(weeklyFileSave.dataset.weeklyFileSave));if(file)await saveWeeklyCopy(currentWeeklyDetail.id,file);return;}
    const weeklyReplace=event.target.closest("[data-weekly-replace]");if(weeklyReplace){await beginWeeklyUpload(currentWeeklyDetail.project_id,currentWeeklyDetail);return;}
    const weeklyDirectory=event.target.closest("[data-weekly-report-directory]");if(weeklyDirectory){await invoke("weekly.open_directory",{report_id:Number(weeklyDirectory.dataset.weeklyReportDirectory)});return;}
  });

  document.addEventListener("change",async event=>{if(event.target.matches("[data-task-check-page]")){const page=paginate(taskFiltered,taskPage,taskPageSize).items;page.forEach(item=>event.target.checked?taskSelection.add(item.id):taskSelection.delete(item.id));await tasks();}if(event.target.matches("[data-weekly-check-page]")){const page=paginate(weeklyItems,weeklyPage,weeklyPageSize).items;page.forEach(item=>event.target.checked?weeklySelection.add(item.id):weeklySelection.delete(item.id));await weeklyLibrary();}});
  $("#task-form").addEventListener("submit",saveTask);$("#event-form").addEventListener("submit",saveEvent);$("#weekly-upload-form").addEventListener("submit",importWeeklyFile);
  $("#task-query-button").addEventListener("click",()=>{taskPage=1;tasks();});$("#task-query-reset").addEventListener("click",()=>{for(const id of ["task-search","task-project-filter","task-status-filter","task-date-start","task-date-end"])$("#"+id).value="";taskPage=1;tasks();});
  $("#calendar-prev").addEventListener("click",()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);calendar();});$("#calendar-next").addEventListener("click",()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);calendar();});$("#calendar-today").addEventListener("click",()=>{calendarCursor=new Date();$("#calendar-date").value="";calendar();});
  document.addEventListener("click",event=>{if(event.target.closest("#calendar-clear-date")){const input=$("#calendar-date");if(input)input.value="";calendarCursor=new Date();calendar();}});
  $("#calendar-year").addEventListener("change",event=>{calendarCursor.setFullYear(Number(event.target.value));calendar();});$("#calendar-month").addEventListener("change",event=>{calendarCursor.setMonth(Number(event.target.value));calendar();});$("#calendar-locate").addEventListener("click",()=>{const value=$("#calendar-date").value;if(!value)return toast("请选择定位日期");calendarCursor=new Date(`${value}T12:00:00`);calendar();});
  $("#weekly-prev").addEventListener("click",()=>{weeklyCursor.setDate(weeklyCursor.getDate()-7);weekly();});$("#weekly-next").addEventListener("click",()=>{weeklyCursor.setDate(weeklyCursor.getDate()+7);weekly();});$("#weekly-today").addEventListener("click",()=>{weeklyCursor=new Date();weekly();});$("#save-weekly").addEventListener("click",saveWeekly);
  $("#weekly-upload").addEventListener("click",()=>beginWeeklyUpload());$("#weekly-open-directory").addEventListener("click",()=>invoke("weekly.open_directory",{}));
  $("#weekly-query-button").addEventListener("click",()=>{weeklyPage=1;weeklyLibrary();});$("#weekly-query-reset").addEventListener("click",()=>{for(const id of ["weekly-search","weekly-date-start","weekly-date-end","weekly-project-filter","weekly-status-filter"])$("#"+id).value="";weeklyPage=1;weeklyLibrary();});
  for(const id of ["ppt-project","ppt-start","ppt-end"])$("#"+id).addEventListener("change",updatePptPreview);$("#ppt-generate").addEventListener("click",generatePpt);
  R.beginWeeklyUpload=beginWeeklyUpload;R.register("tasks",{load:tasks});R.register("calendar",{load:calendar});R.register("weekly",{load:weekly,save:saveWeekly});R.register("weekly-library",{load:async params=>{await weeklyLibrary();if(params?.id)await showWeeklyDetail(Number(params.id));}});R.register("weekly-ppt",{load:ppt});
})();
