(() => {
  "use strict";
  const R=window.RLab,{$,$$,state,invoke,navigate,icons,toast,escapeHtml,dateLabel,statusBadge,emptyRow,nativeDialog,openDialog,paginate,renderPagination,setAssistantContext}=R;
  const fields=["title","status","experiment_date","executor_snapshot","location","objective","background","hypothesis","design","materials_conditions","expected_result","actual_process_summary","actual_result","analysis","conclusion","next_steps"];
  let selectedExportId=null,projectSection="overview",recordsPage=1,recordsPageSize=20,recordItems=[],recordSelection=new Set();
  let exportPage=1,exportPageSize=20,exportItems=[],exportSelection=new Set();
  let projectsPage=1,projectsPageSize=20,projectItems=[],projectSelection=new Set(),homeCalendarEvents=new Map();
  const projectResourceState=new Map(),projectPicker={type:null,items:[],selection:new Set(),page:1,pageSize:10,search:""};
  const recordEditSurface=$("#record-edit-surface"),recordInlineDetail=$("#record-inline-detail");
  if(recordEditSurface&&recordInlineDetail)recordEditSurface.append(recordInlineDetail);

  async function home(){
    const data=state.dashboard||{projects:[],recent_records:[],counts:{}};const records=data.recent_records||[];const resume=records[0];
    if(resume){$("#resume-strip").hidden=false;$("#resume-strip").dataset.recordId=resume.id;$("#resume-title").textContent=resume.title;$("#resume-project").textContent=`所属项目：${resume.project_title}`;$("#resume-time").textContent=`最后编辑：${dateLabel(resume.updated_at,true)}`;}else $("#resume-strip").hidden=true;
    const counts=data.counts||{};const focus=[["flask-conical","今日实验",`${counts.in_progress||0} 项正在进行`,counts.in_progress||0,"records"],["scan-line","待分析记录",`${counts.awaiting_analysis||0} 条需要处理`,counts.awaiting_analysis||0,"records",{status:"awaiting_analysis"}],["folder-kanban","活跃项目",`${data.projects?.length||0} 个项目`,data.projects?.length||0,"projects"],["calendar-check","本周周报","周日 23:59","待完成","weekly"]];
    $("#focus-list").innerHTML=focus.map(x=>`<button class="focus-item" data-home-focus-view="${x[4]}" ${x[5]?`data-home-focus-params='${escapeHtml(JSON.stringify(x[5]))}'`:""} type="button"><span class="object-icon"><i data-lucide="${x[0]}"></i></span><span><b>${x[1]}</b><small>${x[2]}</small></span><strong>${x[3]}</strong><i data-lucide="chevron-right"></i></button>`).join("");
    $("#recent-records").innerHTML=records.length?records.slice(0,5).map(item=>`<tr data-open-record="${item.id}"><td><span class="record-cell"><i data-lucide="flask-conical"></i>${escapeHtml(item.title)}</span></td><td>${escapeHtml(item.project_title)}</td><td>${statusBadge(item.status)}</td><td>${dateLabel(item.updated_at,true)}</td><td><i data-lucide="chevron-right"></i></td></tr>`).join(""):emptyRow(5,"尚无实验记录。新建记录后可从这里继续工作。");
    $("#active-projects").innerHTML=data.projects?.length?data.projects.slice(0,4).map(item=>`<tr data-open-project="${item.id}"><td><span class="record-cell"><i data-lucide="folder-kanban"></i>${escapeHtml(item.title)}</span></td><td>${escapeHtml(item.objective||"—")}</td><td>${item.record_count||0}</td><td>${item.record_count?"继续完善实验记录":"创建第一条实验记录"}</td></tr>`).join(""):emptyRow(4,"尚无项目。建立项目后再添加实验记录。");
    try{const files=await invoke("library.list",{});$("#recent-materials").innerHTML=files.slice(0,3).map(item=>`<button data-view="files"><i data-lucide="file"></i><span><b>${escapeHtml(item.display_name)}</b><small>${dateLabel(item.updated_at,true)}</small></span></button>`).join("")||`<div class="empty-mini"><i data-lucide="files"></i><span>尚无本地资料</span></div>`;}catch(_){$("#recent-materials").innerHTML="";}
    const now=new Date(),monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(now.getDate()-((now.getDay()+6)%7));const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);const isoDay=value=>{const year=value.getFullYear(),month=String(value.getMonth()+1).padStart(2,"0"),day=String(value.getDate()).padStart(2,"0");return `${year}-${month}-${day}`;};
    try{const events=await invoke("calendar.list",{start:isoDay(monday),end:isoDay(sunday)});homeCalendarEvents=new Map(events.map(item=>[String(item.id),item]));}catch(_){homeCalendarEvents.clear();}
    $("#week-row").innerHTML=["一","二","三","四","五","六","日"].map((name,index)=>{const day=new Date(monday);day.setDate(monday.getDate()+index);const key=isoDay(day),items=[...homeCalendarEvents.values()].filter(item=>String(item.date).slice(0,10)===key);return `<button class="day ${day.toDateString()===now.toDateString()?"today":""}" type="button" data-home-calendar-day="${key}" title="查看 ${key} 日程"><span>周${name}</span><b>${day.getDate()}</b>${items.length?`<small class="day-schedule-count">${items.length} 项日程</small><span class="day-schedule-list">${items.slice(0,2).map(item=>`<em data-home-calendar-event="${escapeHtml(item.id)}">${escapeHtml(item.title)}</em>`).join("")}${items.length>2?`<em>+${items.length-2} 项</em>`:""}</span>`:`<small class="day-schedule-count empty">无日程</small>`}</button>`;}).join("");icons();
  }

  async function projects(){
    projectItems=await invoke("project.list",{search:$("#project-search").value.trim()});state.projects=projectItems;R.fillProjectOptions();$("#project-count").textContent=`${projectItems.length} 个项目`;
    const pageData=paginate(projectItems,projectsPage,projectsPageSize);projectsPage=pageData.page;
    $("#project-list").innerHTML=pageData.items.length?pageData.items.map(item=>`<tr><td class="check-column"><input type="checkbox" data-select-project="${item.id}" ${projectSelection.has(item.id)?"checked":""} aria-label="选择 ${escapeHtml(item.title)}"></td><td data-open-project="${item.id}"><span class="record-cell"><i data-lucide="folder-kanban"></i><span>${escapeHtml(item.title)}${item.code?`<small>${escapeHtml(item.code)}</small>`:""}</span></span></td><td data-open-project="${item.id}">${escapeHtml(item.objective||"—")}</td><td data-open-project="${item.id}">${statusBadge(item.status)}</td><td data-open-project="${item.id}">${item.record_count||0}</td><td data-open-project="${item.id}">${dateLabel(item.updated_at,true)}</td></tr>`).join(""):emptyRow(6,"没有匹配的项目。");
    renderPagination($("#project-pagination"),pageData,page=>{projectsPage=page;projects();},size=>{projectsPageSize=size;projectsPage=1;projects();});updateProjectSelection();icons();
  }
  function updateProjectSelection(){const bar=$("#project-bulk-bar");if(!bar)return;bar.hidden=!projectSelection.size;bar.querySelector("[data-selected-count]").textContent=projectSelection.size;const visible=$$('[data-select-project]');$("#project-select-page").checked=visible.length>0&&visible.every(box=>box.checked);}

  async function projectWorkbench(params){
    const id=Number(params.id||state.currentProject?.id);if(!id)return navigate("projects");
    const freshProjects=await invoke("project.list",{}),project=freshProjects.find(x=>x.id===id);if(!project)return navigate("projects");state.projects=freshProjects;R.fillProjectOptions();
    state.currentProject=project;$("#project-workbench-title").textContent=project.title;const codeNode=$("#project-workbench-code");codeNode.textContent=project.code||"";codeNode.hidden=!project.code;setAssistantContext();await renderProjectSection(projectSection);icons();
  }

  async function renderProjectSection(section){
    if(!state.currentProject)return;projectSection=section;$$('[data-project-section]').forEach(x=>{const active=x.dataset.projectSection===section;x.classList.toggle("active",active);x.setAttribute("aria-selected",String(active));x.tabIndex=active?0:-1;});const id=state.currentProject.id,node=$("#project-workbench-content"),labels={overview:"项目概览",records:"项目实验记录",literature:"项目文献",notes:"项目笔记",files:"项目文件",tasks:"项目任务",weekly:"项目周报"},records=await invoke("record.list",{project_id:id});
    if(section==="overview"){node.innerHTML=`<div class="workbench-grid"><section class="panel project-brief"><header><h2>研究目标</h2></header><p>${escapeHtml(state.currentProject.objective||"尚未填写研究目标。")}</p></section><section class="panel"><header><h2>项目指标</h2></header><div class="metric-row">${[["实验记录",records.length],["进行中",records.filter(x=>x.status==="in_progress").length],["已完成",records.filter(x=>x.status==="completed").length]].map(x=>`<div><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("")}</div></section><section class="panel wide"><header><h2>最近实验记录</h2></header><div class="table-wrap"><table><tbody>${records.slice(0,8).map(item=>`<tr data-open-record="${item.id}"><td><span class="record-cell"><i data-lucide="flask-conical"></i>${escapeHtml(item.title)}</span></td><td>${statusBadge(item.status)}</td><td>${dateLabel(item.experiment_date)}</td><td>${dateLabel(item.updated_at,true)}</td></tr>`).join("")||emptyRow(4,"该项目还没有实验记录。")}</tbody></table></div></section></div>`;icons();return;}
    let items=[],add="";if(section==="records"){items=records;add=`<button class="button primary" data-open="record-dialog"><i data-lucide="plus"></i>新建实验记录</button>`;}if(section==="literature"){items=await invoke("literature.list",{project_id:id});add=`<button class="button" data-project-add="literature"><i data-lucide="library"></i>从总文献库添加</button><button class="button primary" data-open="literature-dialog"><i data-lucide="plus"></i>导入新文献</button>`;}if(section==="notes"){items=await invoke("note.list",{project_id:id});add=`<button class="button" data-project-add="notes"><i data-lucide="notebook-tabs"></i>从总笔记库添加</button><button class="button primary" data-project-new-note><i data-lucide="plus"></i>新建笔记</button>`;}if(section==="files"){items=await invoke("library.list",{project_id:id});add=`<button class="button primary" id="project-import-file"><i data-lucide="file-plus-2"></i>导入文件</button>`;}if(section==="tasks"){items=await invoke("task.list",{scope:"all",project_id:id});add=`<button class="button primary" data-open="task-dialog"><i data-lucide="plus"></i>新建任务</button>`;}if(section==="weekly"){items=await invoke("weekly.list",{project_id:id});add=`<button class="button primary" data-project-upload-weekly><i data-lucide="upload"></i>上传周总结</button>`;}
    const local=projectResourceState.get(section)||{page:1,pageSize:20,search:"",selection:new Set()};projectResourceState.set(section,local);const query=local.search.toLowerCase(),filtered=items.filter(item=>!query||JSON.stringify(item).toLowerCase().includes(query)),page=paginate(filtered,local.page,local.pageSize);local.page=page.page;const columns=page.items.map(item=>projectResourceRow(section,item,local.selection.has(item.id))).join("");node.innerHTML=`<div class="project-section-head"><div><h2>${labels[section]}</h2><p class="muted">${filtered.length} 项 · 仅显示当前项目内容</p></div>${add}</div><div class="query-toolbar"><label class="grow"><span>查询</span><div><i data-lucide="search"></i><input data-project-resource-search type="search" value="${escapeHtml(local.search)}" placeholder="输入名称或关键词"></div></label><button class="button primary" data-project-resource-query>查询</button></div><section class="panel project-resource-list">${columns||`<div class="empty-state"><p>当前项目尚无${labels[section].replace("项目","")}。</p></div>`}</section><footer class="list-pagination" id="project-resource-pagination"></footer>`;renderPagination($("#project-resource-pagination"),page,value=>{local.page=value;renderProjectSection(section);},value=>{local.pageSize=value;local.page=1;renderProjectSection(section);});icons();
  }
  function projectResourceRow(section,item,selected){let subtitle="",middle="",tail="";if(section==="records"){subtitle=item.record_code;middle=statusBadge(item.status);tail=dateLabel(item.experiment_date);}if(section==="literature"){subtitle=(item.authors||[]).join("、")||item.journal||"";middle=statusBadge(item.read_status);tail=item.year||"—";}if(section==="notes"){subtitle=item.excerpt||"";middle=escapeHtml(item.kind);tail=dateLabel(item.updated_at,true);}if(section==="files"){subtitle=item.path||"";middle=escapeHtml(item.kind);tail=R.formatBytes(item.size_bytes);}if(section==="tasks"){subtitle=item.notes||"";middle=statusBadge(item.status);tail=dateLabel(item.deadline);}if(section==="weekly"){subtitle=item.summary||"";middle=statusBadge(item.status);tail=dateLabel(item.report_date);}return `<div class="project-resource-row" data-project-resource-open="${section}" data-resource-id="${item.id}"><input type="checkbox" data-project-resource-select="${item.id}" ${selected?"checked":""}><span><b>${escapeHtml(item.title||item.display_name)}</b><small>${escapeHtml(subtitle)}</small></span><span>${middle}</span><span>${tail}</span><button class="icon-button row-menu-button" title="打开详情" aria-label="打开 ${escapeHtml(item.title||item.display_name)}"><i data-lucide="arrow-up-right"></i></button></div>`;}

  async function openProjectPicker(type){projectPicker.type=type;projectPicker.page=1;projectPicker.search="";projectPicker.selection.clear();projectPicker.items=await invoke(type==="literature"?"literature.list":"note.list",{});let dialog=$("#project-resource-picker");if(!dialog){dialog=document.createElement("dialog");dialog.id="project-resource-picker";document.body.append(dialog);dialog.addEventListener("close",()=>{dialog._trigger?.focus?.();});}dialog._trigger=document.activeElement;renderProjectPicker();dialog.showModal();}
  function renderProjectPicker(){const dialog=$("#project-resource-picker"),items=projectPicker.items.filter(item=>!projectPicker.search||JSON.stringify(item).toLowerCase().includes(projectPicker.search.toLowerCase())),page=paginate(items,projectPicker.page,projectPicker.pageSize);projectPicker.page=page.page;const pageSelected=page.items.length&&page.items.every(item=>projectPicker.selection.has(item.id));dialog.innerHTML=`<form method="dialog" class="resource-picker"><header><div><h2>从总${projectPicker.type==="literature"?"文献":"笔记"}库添加</h2><p>选择后关联到 ${escapeHtml(state.currentProject.title)}</p></div><button class="icon-button" value="cancel"><i data-lucide="x"></i></button></header><div class="query-toolbar"><label class="grow"><span>查询</span><div><i data-lucide="search"></i><input data-picker-search value="${escapeHtml(projectPicker.search)}" placeholder="输入标题或关键词"></div></label><button class="button" type="button" data-picker-query>查询</button></div><div class="picker-select-toolbar"><label><input type="checkbox" data-picker-select-page ${pageSelected?"checked":""}>全选当前页</label><button class="text-button" type="button" data-picker-select-filtered>选择全部查询结果（${items.length}）</button><span>已选择 ${projectPicker.selection.size} 项</span></div><div class="picker-list">${page.items.map(item=>`<label><input type="checkbox" data-picker-select="${item.id}" ${projectPicker.selection.has(item.id)?"checked":""}><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.excerpt||(item.authors||[]).join("、")||item.journal||"")}</small></span></label>`).join("")||`<div class="empty-state"><p>没有匹配内容</p></div>`}</div><footer class="list-pagination" id="picker-pagination"></footer><footer><span>已选择 ${projectPicker.selection.size} 项</span><button class="button" value="cancel">取消</button><button class="button primary" type="button" data-picker-apply>添加到项目</button></footer></form>`;renderPagination($("#picker-pagination"),page,value=>{projectPicker.page=value;renderProjectPicker();},value=>{projectPicker.pageSize=value;projectPicker.page=1;renderProjectPicker();});icons();}
  async function applyProjectPicker(){if(!projectPicker.selection.size)return toast("请至少选择一项");const ids=[...projectPicker.selection];if(projectPicker.type==="literature")await invoke("literature.bulk",{ids,action:"project",value:state.currentProject.id});else await invoke("note.bulk",{ids,action:"project",value:state.currentProject.id});$("#project-resource-picker").close();await renderProjectSection(projectPicker.type);toast(`已添加 ${ids.length} 项`);}

  async function records(){
    const detail=$("#record-inline-detail");if(detail)detail.hidden=true;
    const query=$("#record-search").value.trim(),projectId=$("#record-project-filter").value,status=$("#record-status-filter").value,start=$("#record-date-start").value,end=$("#record-date-end").value;const result=await invoke("record.list",{pagination:true,page:recordsPage,page_size:recordsPageSize,search:query,project_id:projectId||null,status,date_start:start,date_end:end});recordItems=result.items;recordItems.serverPagination=result.pagination;const pageData=paginate(recordItems,recordsPage,recordsPageSize);recordsPage=pageData.page;state.records=recordItems;
    $("#record-list").innerHTML=pageData.items.length?pageData.items.map(item=>`<tr data-record-row="${item.id}" class="${recordSelection.has(item.id)?'selected':''}"><td class="check-column"><input type="checkbox" data-select-record="${item.id}" ${recordSelection.has(item.id)?'checked':''}></td><td data-open-record="${item.id}"><span class="record-cell"><i data-lucide="flask-conical"></i><span>${escapeHtml(item.title)}<br><small>${escapeHtml(item.record_code)}</small></span></span></td><td>${escapeHtml(item.project_title)}</td><td>${dateLabel(item.experiment_date)}</td><td>${statusBadge(item.status)}</td><td>${escapeHtml(item.executor_snapshot||"—")}</td><td>${dateLabel(item.updated_at,true)}</td><td><button class="icon-button row-menu-button" data-record-menu="${item.id}" title="更多操作"><i data-lucide="ellipsis"></i></button></td></tr>`).join(""):emptyRow(8,"没有匹配的实验记录。");renderPagination($("#record-pagination"),pageData,page=>{recordsPage=page;records();},size=>{recordsPageSize=size;recordsPage=1;records();});updateRecordSelection();icons();
  }
  function updateRecordSelection(){const bar=$("#record-bulk-bar");bar.hidden=!recordSelection.size;bar.querySelector('[data-selected-count]').textContent=recordSelection.size;const visible=$$('[data-select-record]');$("#record-select-page").checked=visible.length>0&&visible.every(x=>x.checked);}

  function renderSteps(steps){$("#step-list").innerHTML=steps.map((step,index)=>`<div class="step-row" data-step><span class="step-number">${String(index+1).padStart(2,"0")}</span><input name="step-title" maxlength="180" value="${escapeHtml(step.title||"")}" placeholder="步骤标题"><textarea name="step-instruction" rows="2" placeholder="操作说明">${escapeHtml(step.instruction||"")}</textarea><input type="hidden" name="step-id" value="${step.id||""}"><input type="hidden" name="step-duration" value="${step.planned_duration_minutes||""}"><input type="hidden" name="step-checkpoint" value="${escapeHtml(step.checkpoint||"")}"><input type="hidden" name="step-risk" value="${escapeHtml(step.risk||"")}"><input type="hidden" name="step-done" value="${step.is_done?"true":"false"}"><input type="hidden" name="step-deviation" value="${escapeHtml(step.actual_deviation||"")}"><button class="icon-button remove-step" type="button" title="删除步骤"><i data-lucide="trash-2"></i></button></div>`).join("");icons();}
  async function openRecord(params){
    const id=Number(params.id||state.currentRecord?.id);if(!id)return navigate("records");const record=await invoke("record.get",{id});state.currentRecord=record;state.dirty=false;
    if(!$("#record-list")?.children.length)await records();
    const detail=$("#record-inline-detail");if(detail)detail.hidden=false;
    $("#record-editor-title").textContent=record.title;$("#record-code").textContent=record.record_code;const form=$("#record-form");fields.forEach(name=>{if(form.elements[name])form.elements[name].value=record[name]??"";});renderSteps(record.steps||[]);setSaveState("saved");
    setAssistantContext();icons();
  }
  function collectRecord(){const payload={id:state.currentRecord.id};new FormData($("#record-form")).forEach((value,key)=>payload[key]=value);payload.steps=$$("[data-step]",$("#record-form")).map(row=>({id:Number($("[name=step-id]",row)?.value)||null,title:$("[name=step-title]",row).value,instruction:$("[name=step-instruction]",row).value,planned_duration_minutes:Number($("[name=step-duration]",row)?.value)||null,checkpoint:$("[name=step-checkpoint]",row)?.value||"",risk:$("[name=step-risk]",row)?.value||"",is_done:$("[name=step-done]",row)?.value==="true",actual_deviation:$("[name=step-deviation]",row)?.value||""}));return payload;}
  function setSaveState(mode,message=""){const node=$("#save-state");node.className=`save-state ${mode}`;node.innerHTML=mode==="saving"?`<i data-lucide="loader-circle"></i>正在保存`:mode==="error"?`<i data-lucide="circle-alert"></i>${escapeHtml(message||"保存失败")}`:`<i data-lucide="circle-check"></i>已保存`;icons();}
  async function saveRecord(){if(!state.currentRecord||!state.dirty)return;clearTimeout(state.saveTimer);setSaveState("saving");try{const saved=await invoke("record.update",collectRecord(),state.currentRecord.row_version);state.currentRecord=saved;state.dirty=false;$("#record-editor-title").textContent=saved.title;setSaveState("saved");}catch(error){setSaveState("error",error.message);toast(error.message);}}
  function markDirty(){if(!state.currentRecord)return;state.dirty=true;setSaveState("saving");clearTimeout(state.saveTimer);state.saveTimer=setTimeout(saveRecord,900);}

  async function recordFiles(params){const id=Number(params.id||state.currentRecord?.id);if(!id)return navigate("records");if(!state.currentRecord||state.currentRecord.id!==id)state.currentRecord=await invoke("record.get",{id});$("#record-files-title").textContent=state.currentRecord.title;const items=await invoke("library.list",{record_id:id});$("#record-file-list").innerHTML=items.length?items.map(item=>`<tr><td>${escapeHtml(item.display_name)}</td><td>${escapeHtml(item.kind)}</td><td>${escapeHtml(item.storage_mode)}</td><td>${statusBadge(item.link_status)}</td><td>${R.formatBytes(item.size_bytes)}</td><td>${dateLabel(item.updated_at,true)}</td></tr>`).join(""):emptyRow(6,"尚未关联文件。使用“导入文件”添加实验数据或结果图。");icons();}
  async function recordRead(params){const id=Number(params.id||state.currentRecord?.id);if(!id)return navigate("records");const r=await invoke("record.get",{id});state.currentRecord=r;$("#record-read-title").textContent=r.title;const sections=[["实验目的",r.objective],["背景与假设",[r.background,r.hypothesis].filter(Boolean).join("\n")],["实验设计",r.design],["材料与条件",r.materials_conditions],["实验步骤",(r.steps||[]).map((s,i)=>`${i+1}. ${s.title}\n${s.instruction}`).join("\n\n")],["预期结果",r.expected_result],["实际过程",r.actual_process_summary],["实际结果",r.actual_result],["分析与结论",[r.analysis,r.conclusion].filter(Boolean).join("\n")],["下一步",r.next_steps]];$("#record-reading-surface").innerHTML=`<header><p>${escapeHtml(r.record_code)} · ${escapeHtml(r.project_title)} · ${dateLabel(r.experiment_date)}</p><h1>${escapeHtml(r.title)}</h1></header>${sections.map(x=>`<section><h2>${x[0]}</h2><p>${escapeHtml(x[1]||"未填写").replaceAll("\n","<br>")}</p></section>`).join("")}`;}
  async function recordHistory(params){const id=Number(params.id||state.currentRecord?.id);if(!id)return navigate("records");const r=await invoke("record.get",{id});state.currentRecord=r;const revisions=r.revisions||[];$("#record-history-list").innerHTML=revisions.length?revisions.map(item=>`<article><span class="timeline-dot"></span><div><h3>${escapeHtml(item.reason)}</h3><p>${escapeHtml(item.scope)} · ${dateLabel(item.created_at,true)}</p></div><button class="button compact" type="button">查看差异</button></article>`).join(""):`<div class="empty-state"><i data-lucide="history"></i><p>尚无修订历史。第一次保存后会形成修订。</p></div>`;icons();}

  function exportQuery(){return {pagination:true,page:exportPage,page_size:exportPageSize,search:$("#export-search").value.trim(),project_id:$("#export-project-filter").value||null,status:$("#export-status-filter").value||null,date_start:$("#export-date-start").value,date_end:$("#export-date-end").value};}
  function updateExportSelection(){const bar=$("#export-selection-count"),target=$("#export-target-count"),visible=$$('[data-export-select]');if(bar)bar.textContent=`已选 ${exportSelection.size} 条`;if(target)target.textContent=exportSelection.size?`将导出 ${exportSelection.size} 条记录`:`未选择记录`;const pageBox=$("#export-select-page");if(pageBox)pageBox.checked=visible.length>0&&visible.every(box=>box.checked);$("#export-count").textContent=`${exportItems.serverPagination?.total??exportItems.length} 条记录`;}
  async function recordExport(){
    R.fillProjectOptions();const result=await invoke("record.list",exportQuery());exportItems=result.items||[];exportItems.serverPagination=result.pagination;
    const pageData=paginate(exportItems,exportPage,exportPageSize);exportPage=pageData.page;
    $("#export-record-list").innerHTML=pageData.items.length?pageData.items.map(item=>`<label class="check-row ${exportSelection.has(item.id)?"selected":""}"><input type="checkbox" data-export-select="${item.id}" ${exportSelection.has(item.id)?"checked":""}><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.record_code)} · ${escapeHtml(item.project_title)} · ${dateLabel(item.experiment_date)}</small></span><em>${statusBadge(item.status)}</em></label>`).join(""):`<div class="empty-state"><p>没有匹配的实验记录</p></div>`;
    renderPagination($("#export-pagination"),pageData,page=>{exportPage=page;recordExport();},size=>{exportPageSize=size;exportPage=1;recordExport();});updateExportSelection();
    const first=[...exportSelection][0];if(first)selectExportRecord(first);else {$("#export-preview-title").textContent="选择一条实验记录";$("#export-preview-body").innerHTML=`<div class="empty-state"><p>勾选记录后查看导出摘要。</p></div>`;}
  }
  async function selectExportRecord(id){selectedExportId=Number(id);const r=await invoke("record.get",{id:selectedExportId});$("#export-preview-title").textContent=r.title;$("#export-preview-body").innerHTML=`<dl class="preview-summary"><div><dt>记录编号</dt><dd>${escapeHtml(r.record_code)}</dd></div><div><dt>所属项目</dt><dd>${escapeHtml(r.project_title)}</dd></div><div><dt>实验日期</dt><dd>${dateLabel(r.experiment_date)}</dd></div><div><dt>步骤</dt><dd>${r.steps?.length||0} 条</dd></div><div><dt>结论</dt><dd>${escapeHtml(r.conclusion||"未填写")}</dd></div></dl>`;}
  async function exportSelected(){const ids=[...exportSelection];if(!ids.length)return toast("请先选择实验记录");const extension=$("#export-format").value;const paths=await nativeDialog("dialog.select_directory",{});if(!paths.length)return;try{const result=await invoke("record.export.batch",{ids,directory:paths[0],format:extension});$("#export-result").textContent=`已导出 ${result.count} 条，共 ${R.formatBytes(result.size_bytes)}`;toast(`已批量导出 ${result.count} 条实验记录`);}catch(error){toast(error.message);}}

  function prepareProjectDialog(project){const form=$("#project-form"),editing=Boolean(project);form.elements.id.value=editing?project.id:"";form.elements.row_version.value=editing?project.row_version:"";form.elements.title.value=editing?project.title:"";form.elements.code.value=editing?project.code||"":"";form.elements.status.value=editing?project.status||"active":"active";form.elements.objective.value=editing?project.objective||"":"";$("#project-dialog-title").textContent=editing?"编辑项目":"新建项目";$("#project-dialog-submit").textContent=editing?"保存项目":"创建项目";$(".form-error",form).textContent="";if(!editing)form.elements.title.focus();}
  async function submitProject(event){event.preventDefault();const form=event.currentTarget;const payload=Object.fromEntries(new FormData(form)),id=Number(payload.id)||null;try{const saved=id?await invoke("project.update",payload,Number(payload.row_version)):await invoke("project.create",payload);form.closest("dialog").close();prepareProjectDialog(null);await R.loadInitial();if(id){state.currentProject=saved;await navigate("project-workbench",{id:saved.id});toast("项目已更新");}else{await navigate("projects");toast("项目已创建");}}catch(error){$(".form-error",form).textContent=error.message;}}
  async function submitRecord(event){event.preventDefault();const form=event.currentTarget;try{const record=await invoke("record.create",Object.fromEntries(new FormData(form)));form.closest("dialog").close();form.reset();await R.loadInitial();await navigate("record-edit",{id:record.id});toast("实验记录草稿已创建");}catch(error){$(".form-error",form).textContent=error.message;}}
  async function openProjectResource(section,id){if(section==="records")return navigate("record-edit",{id});if(section==="literature")return navigate("literature",{id});if(section==="notes")return navigate("notes",{id});if(section==="files")return navigate("files",{id});if(section==="tasks")return navigate("tasks",{id});if(section==="weekly")return navigate("weekly-library",{id});}

  document.addEventListener("click",async event=>{
    const homeDay=event.target.closest("[data-home-calendar-day]");if(homeDay){await navigate("calendar",{date:homeDay.dataset.homeCalendarDay});return;}
    const homeEvent=event.target.closest("[data-home-calendar-event]");if(homeEvent){const item=homeCalendarEvents.get(homeEvent.dataset.homeCalendarEvent);await navigate("calendar",{date:item?.date||""});return;}
    const focus=event.target.closest("[data-home-focus-view]");if(focus){let params={};try{params=JSON.parse(focus.dataset.homeFocusParams||"{}");}catch(_){ }await navigate(focus.dataset.homeFocusView,params);return;}
    const createProject=event.target.closest('[data-open="project-dialog"]');if(createProject)prepareProjectDialog(null);
    const editProject=event.target.closest("[data-edit-project]");if(editProject){event.preventDefault();prepareProjectDialog(state.currentProject);openDialog("project-dialog");return;}
    const record=event.target.closest("[data-open-record]");if(record){event.preventDefault();navigate("record-edit",{id:Number(record.dataset.openRecord)});}
    const project=event.target.closest("[data-open-project]");if(project)navigate("project-workbench",{id:Number(project.dataset.openProject)});
    const projectResource=event.target.closest("[data-project-resource-open]");if(projectResource&&!event.target.closest("input")){await openProjectResource(projectResource.dataset.projectResourceOpen,Number(projectResource.dataset.resourceId));return;}
    const projectTab=event.target.closest("[data-project-section]");if(projectTab)renderProjectSection(projectTab.dataset.projectSection);
    const projectAdd=event.target.closest("[data-project-add]");if(projectAdd)openProjectPicker(projectAdd.dataset.projectAdd);
    const pickerQuery=event.target.closest("[data-picker-query]");if(pickerQuery){projectPicker.search=$("[data-picker-search]").value.trim();projectPicker.page=1;renderProjectPicker();}
    if(event.target.closest("[data-picker-select-filtered]")){const items=projectPicker.items.filter(item=>!projectPicker.search||JSON.stringify(item).toLowerCase().includes(projectPicker.search.toLowerCase()));items.forEach(item=>projectPicker.selection.add(item.id));renderProjectPicker();}
    if(event.target.closest("[data-picker-apply]"))applyProjectPicker();
    const projectQuery=event.target.closest("[data-project-resource-query]");if(projectQuery){const local=projectResourceState.get(projectSection);local.search=$("[data-project-resource-search]").value.trim();local.page=1;renderProjectSection(projectSection);}
    const projectNewNote=event.target.closest("[data-project-new-note]");if(projectNewNote){navigate("notes");setTimeout(()=>{$("#new-note")?.click();if($("#note-project"))$("#note-project").value=state.currentProject?.id||"";},0);}
    if(event.target.closest("#project-import-file"))navigate("files");
    if(event.target.closest("[data-project-upload-weekly]")){await navigate("weekly-library");await R.beginWeeklyUpload?.(state.currentProject?.id||null);}
    const remove=event.target.closest(".remove-step");if(remove){remove.closest("[data-step]").remove();$$('.step-number').forEach((node,index)=>node.textContent=String(index+1).padStart(2,"0"));markDirty();}
    const clear=event.target.closest("[data-clear-selection]");if(clear){recordSelection.clear();records();}
    const allMatches=event.target.closest("[data-select-all-matches]");if(allMatches){recordItems.forEach(item=>recordSelection.add(item.id));updateRecordSelection();toast(`已选择当前筛选的 ${recordItems.length} 项`);}
    const bulk=event.target.closest("[data-record-bulk]");if(bulk)recordBulk(bulk.dataset.recordBulk);
    const projectBulkButton=event.target.closest("[data-project-bulk]");if(projectBulkButton){await projectBulk(projectBulkButton.dataset.projectBulk);return;}
    if(event.target.closest("[data-project-select-all]")){projectItems.forEach(item=>projectSelection.add(item.id));updateProjectSelection();toast(`已选择当前筛选的 ${projectItems.length} 个项目`);return;}
    if(event.target.closest("[data-project-clear]")){projectSelection.clear();await projects();return;}
    if(event.target.closest("#record-inline-close")){if(state.dirty&&!confirm("当前实验记录尚未保存，仍要关闭编辑器吗？"))return;$("#record-inline-detail").hidden=true;state.currentRecord=null;state.dirty=false;setAssistantContext();await navigate("records");return;}
    if(event.target.closest("#export-select-all")){const query=exportQuery();delete query.pagination;delete query.page;delete query.page_size;const all=await invoke("record.list",query);const items=Array.isArray(all)?all:(all.items||[]);items.forEach(item=>exportSelection.add(item.id));await recordExport();toast(`已选择当前查询的 ${items.length} 条记录`);return;}
    if(event.target.closest("#export-clear-selection")){exportSelection.clear();selectedExportId=null;$$('[data-export-select]').forEach(box=>{box.checked=false;box.closest('.check-row')?.classList.remove('selected');});updateExportSelection();$("#export-preview-title").textContent="选择一条实验记录";$("#export-preview-body").innerHTML=`<div class="empty-state"><p>勾选记录后查看导出摘要。</p></div>`;return;}
  });
  document.addEventListener("change",event=>{if(event.target.matches('[data-select-record]')){const id=Number(event.target.dataset.selectRecord);event.target.checked?recordSelection.add(id):recordSelection.delete(id);event.target.closest('tr')?.classList.toggle('selected',event.target.checked);updateRecordSelection();}if(event.target.matches('[data-select-project]')){const id=Number(event.target.dataset.selectProject);event.target.checked?projectSelection.add(id):projectSelection.delete(id);event.target.closest('tr')?.classList.toggle('selected',event.target.checked);updateProjectSelection();}if(event.target.matches('[data-project-resource-select]')){const local=projectResourceState.get(projectSection),id=Number(event.target.dataset.projectResourceSelect);event.target.checked?local.selection.add(id):local.selection.delete(id);}if(event.target.matches('[data-picker-select]')){const id=Number(event.target.dataset.pickerSelect);event.target.checked?projectPicker.selection.add(id):projectPicker.selection.delete(id);renderProjectPicker();}if(event.target.matches('[data-picker-select-page]')){const items=projectPicker.items.filter(item=>!projectPicker.search||JSON.stringify(item).toLowerCase().includes(projectPicker.search.toLowerCase())),page=paginate(items,projectPicker.page,projectPicker.pageSize);page.items.forEach(item=>event.target.checked?projectPicker.selection.add(item.id):projectPicker.selection.delete(item.id));renderProjectPicker();}if(event.target.matches('[data-export-select]')){const id=Number(event.target.dataset.exportSelect);event.target.checked?exportSelection.add(id):exportSelection.delete(id);event.target.closest('.check-row')?.classList.toggle('selected',event.target.checked);if(event.target.checked)selectExportRecord(id);updateExportSelection();}if(event.target.matches('#export-select-page')){$$('[data-export-select]').forEach(box=>{box.checked=event.target.checked;const id=Number(box.dataset.exportSelect);event.target.checked?exportSelection.add(id):exportSelection.delete(id);box.closest('.check-row')?.classList.toggle('selected',event.target.checked);});updateExportSelection();}});
  $("#project-form").addEventListener("submit",submitProject);$("#create-record-form").addEventListener("submit",submitRecord);
  $("#project-search").addEventListener("input",()=>{clearTimeout(state.projectTimer);projectsPage=1;state.projectTimer=setTimeout(projects,180);});$("#project-select-page").addEventListener("change",event=>{$$('[data-select-project]').forEach(box=>{box.checked=event.target.checked;const id=Number(box.dataset.selectProject);event.target.checked?projectSelection.add(id):projectSelection.delete(id);box.closest('tr')?.classList.toggle('selected',event.target.checked);});updateProjectSelection();});$("#record-query-button").addEventListener("click",()=>{recordsPage=1;records();});for(const id of ["record-search","record-date-start","record-date-end","record-project-filter","record-status-filter"])$("#"+id).addEventListener(id==="record-search"?"keydown":"change",event=>{if(id!=="record-search"||event.key==="Enter"){recordsPage=1;records();}});$("#record-query-reset").addEventListener("click",()=>{for(const id of ["record-search","record-date-start","record-date-end","record-project-filter","record-status-filter"])$("#"+id).value="";recordsPage=1;records();});$("#record-select-page").addEventListener("change",event=>{$$('[data-select-record]').forEach(box=>{box.checked=event.target.checked;const id=Number(box.dataset.selectRecord);event.target.checked?recordSelection.add(id):recordSelection.delete(id);box.closest('tr')?.classList.toggle('selected',event.target.checked);});updateRecordSelection();});
  $("#record-form").addEventListener("input",markDirty);$("#record-form").addEventListener("change",markDirty);$("#save-record").addEventListener("click",()=>{state.dirty=true;saveRecord();});
  $("#add-step").addEventListener("click",()=>{const steps=$$("[data-step]").map(row=>({title:$("[name=step-title]",row).value,instruction:$("[name=step-instruction]",row).value}));steps.push({});renderSteps(steps);markDirty();});
  $("#resume-strip").addEventListener("click",event=>navigate("record-edit",{id:Number(event.currentTarget.dataset.recordId)}));
  $("#export-record-button").addEventListener("click",exportSelected);$("#export-query-button").addEventListener("click",()=>{exportPage=1;recordExport();});$("#export-query-reset").addEventListener("click",()=>{for(const id of ["export-search","export-date-start","export-date-end","export-project-filter","export-status-filter"])$("#"+id).value="";exportPage=1;recordExport();});for(const id of ["export-search","export-date-start","export-date-end","export-project-filter","export-status-filter"])$("#"+id).addEventListener(id==="export-search"?"keydown":"change",event=>{if(id!=="export-search"||event.key==="Enter"){exportPage=1;recordExport();}});

  R.register("home",{load:home});R.register("projects",{load:projects});R.register("project-workbench",{load:projectWorkbench});R.register("records",{load:records});R.register("record-edit",{load:openRecord,save:saveRecord});R.register("record-files",{load:recordFiles});R.register("record-read",{load:recordRead});R.register("record-history",{load:recordHistory});R.register("record-export",{load:recordExport});

  async function recordBulk(action){const ids=[...recordSelection];if(!ids.length)return;const payload={ids,action};if(action==="trash"){if(!await R.confirmAction("移入回收站",`确认将已选择的 ${ids.length} 条实验记录移入回收站吗？`))return;}else if(action==="status"){payload.value=await bulkChoice("批量调整状态",[["in_progress","进行中"],["awaiting_analysis","待分析"],["completed","已完成"],["archived","已归档"]]);if(!payload.value)return;}else{payload.value=Number(await bulkChoice("批量调整项目",state.projects.map(x=>[String(x.id),x.title])));if(!payload.value)return;}await invoke("record.bulk",payload);recordSelection.clear();await records();toast("批量操作已完成");}
  async function projectBulk(action){const ids=[...projectSelection];if(!ids.length)return;if(action==="trash"){if(!await R.confirmAction("移入回收站",`确认将已选择的 ${ids.length} 个项目移入回收站吗？`))return;await invoke("project.bulk",{ids,action:"trash"});projectSelection.clear();await projects();await R.loadInitial();toast("项目已移入回收站");return;}if(action==="status"){const value=await bulkChoice("批量调整项目状态",[["active","进行中"],["paused","已暂停"],["completed","已完成"],["archived","已归档"]]);if(!value)return;await invoke("project.bulk",{ids,action:"status",status:value});projectSelection.clear();await projects();await R.loadInitial();toast("项目状态已批量更新");}}
  function bulkChoice(title,options){return new Promise(resolve=>{const trigger=document.activeElement;let dialog=$("#bulk-choice-dialog");if(!dialog){dialog=document.createElement("dialog");dialog.id="bulk-choice-dialog";document.body.append(dialog);}dialog.innerHTML=`<form method="dialog"><header><div><h2>${escapeHtml(title)}</h2><p>所选项目将统一更新，未选字段保持不变。</p></div></header><label>选择新值<select>${options.map(x=>`<option value="${escapeHtml(x[0])}">${escapeHtml(x[1])}</option>`).join("")}</select></label><footer><button class="button" value="cancel">取消</button><button class="button primary" value="confirm">应用</button></footer></form>`;dialog.addEventListener("close",()=>{const value=dialog.returnValue==="confirm"?dialog.querySelector("select").value:null;trigger?.focus?.();resolve(value);},{once:true});dialog.showModal();});}
})();
